import type { DomainMeta } from './types';

export const DOMAINS: DomainMeta[] = [
  {
    id: 'cyber',
    label: 'Cybersecurity',
    icon: '🔐',
    color: '#EF4444',
    description: 'Threats, defenses, and security engineering',
  },
  {
    id: 'devops',
    label: 'DevOps',
    icon: '⚙️',
    color: '#F97316',
    description: 'CI/CD, containers, and platform engineering',
  },
  {
    id: 'cloud',
    label: 'Cloud',
    icon: '☁️',
    color: '#3B82F6',
    description: 'AWS, Azure, GCP, and cloud-native patterns',
  },
  {
    id: 'networking',
    label: 'Networking',
    icon: '🌐',
    color: '#10B981',
    description: 'Protocols, routing, and network architecture',
  },
  {
    id: 'data',
    label: 'Data',
    icon: '🗄️',
    color: '#8B5CF6',
    description: 'Databases, pipelines, and data engineering',
  },
  {
    id: 'ai',
    label: 'AI & ML',
    icon: '🤖',
    color: '#EC4899',
    description: 'Machine learning, LLMs, and AI infrastructure',
  },
  {
    id: 'syseng',
    label: 'Systems Engineering',
    icon: '🖥️',
    color: '#6366F1',
    description: 'OS, hardware, capacity planning, and reliability',
  },
  {
    id: 'coding',
    label: 'Software Development',
    icon: '💻',
    color: '#14B8A6',
    description: 'Design patterns, testing, APIs, and code quality',
  },
  {
    id: 'integration',
    label: 'Integration',
    icon: '🔗',
    color: '#F472B6',
    description: 'APIs, message queues, webhooks, and middleware',
  },
  {
    id: 'agile',
    label: 'Agile & PM',
    icon: '📋',
    color: '#FBBF24',
    description: 'Scrum, Kanban, estimation, and team practices',
  },
  {
    id: 'governance',
    label: 'IT Governance',
    icon: '🏛️',
    color: '#A78BFA',
    description: 'ITIL, compliance, risk, and change management',
  },
  {
    id: 'observability',
    label: 'Observability & SRE',
    icon: 'pulse',
    color: '#22C55E',
    description: 'Telemetry, reliability, incidents, and SLO trade-offs',
  },
  {
    id: 'identity',
    label: 'Identity & Access',
    icon: 'key',
    color: '#06B6D4',
    description: 'Authentication, authorization, federation, and trust',
  },
  {
    id: 'architecture',
    label: 'Architecture & System Design',
    icon: 'blocks',
    color: '#FB7185',
    description: 'Scale, boundaries, trade-offs, and resilient designs',
  },
  {
    id: 'appsec',
    label: 'App Security & DevSecOps',
    icon: 'shield',
    color: '#F59E0B',
    description: 'Secure software delivery, threat models, and flaws',
  },
];
