import type { DomainMeta } from './types';

export const DOMAINS: DomainMeta[] = [
  {
    id: 'cyber',
    label: 'Cybersecurity',
    icon: '🔐',
    color: '#EF4444',
    description: 'Threats, defenses, and security engineering',
  },
  {
    id: 'devops',
    label: 'DevOps',
    icon: '⚙️',
    color: '#F97316',
    description: 'CI/CD, containers, and platform engineering',
  },
  {
    id: 'cloud',
    label: 'Cloud',
    icon: '☁️',
    color: '#3B82F6',
    description: 'AWS, Azure, GCP, and cloud-native patterns',
  },
  {
    id: 'networking',
    label: 'Networking',
    icon: '🌐',
    color: '#10B981',
    description: 'Protocols, routing, and network architecture',
  },
  {
    id: 'data',
    label: 'Data',
    icon: '🗄️',
    color: '#8B5CF6',
    description: 'Databases, pipelines, and data engineering',
  },
  {
    id: 'ai',
    label: 'AI & ML',
    icon: '🤖',
    color: '#EC4899',
    description: 'Machine learning, LLMs, and AI infrastructure',
  },
  {
    id: 'syseng',
    label: 'Systems Engineering',
    icon: '🖥️',
    color: '#6366F1',
    description: 'OS, hardware, capacity planning, and reliability',
  },
  {
    id: 'coding',
    label: 'Software Development',
    icon: '💻',
    color: '#14B8A6',
    description: 'Design patterns, testing, APIs, and code quality',
  },
  {
    id: 'integration',
    label: 'Integration',
    icon: '🔗',
    color: '#F472B6',
    description: 'APIs, message queues, webhooks, and middleware',
  },
  {
    id: 'agile',
    label: 'Agile & PM',
    icon: '📋',
    color: '#FBBF24',
    description: 'Scrum, Kanban, estimation, and team practices',
  },
  {
    id: 'governance',
    label: 'IT Governance',
    icon: '🏛️',
    color: '#A78BFA',
    description: 'ITIL, compliance, risk, and change management',
  },
];
