import type { Card } from '../types';

type TermSeed = readonly [title: string, subtitle: string];

const domainLabels: Record<Card['domain'], string> = {
  cyber: 'cybersecurity',
  devops: 'DevOps',
  cloud: 'cloud computing',
  networking: 'networking',
  data: 'data engineering',
  ai: 'AI and machine learning',
  syseng: 'systems engineering',
  coding: 'software development',
  integration: 'systems integration',
  agile: 'agile delivery',
  governance: 'IT governance',
  observability: 'observability',
  identity: 'identity and access',
  architecture: 'architecture and system design',
  appsec: 'application security',
};

const domainTags: Record<Card['domain'], readonly string[]> = {
  cyber: ['security', 'risk', 'defense'],
  devops: ['delivery', 'operations', 'automation'],
  cloud: ['cloud', 'operations', 'architecture'],
  networking: ['networking', 'connectivity', 'operations'],
  data: ['data', 'analytics', 'platform'],
  ai: ['AI', 'models', 'platform'],
  syseng: ['systems', 'operations', 'infrastructure'],
  coding: ['development', 'quality', 'design'],
  integration: ['integration', 'API', 'messaging'],
  agile: ['delivery', 'product', 'teamwork'],
  governance: ['governance', 'risk', 'compliance'],
  observability: ['telemetry', 'reliability', 'operations'],
  identity: ['identity', 'access', 'trust'],
  architecture: ['architecture', 'design', 'trade-offs'],
  appsec: ['security', 'application', 'delivery'],
};

const domainConfusions: Record<Card['domain'], string> = {
  cyber:
    'This term is sometimes treated as a tool purchase, but the important part is how it changes prevention, detection, response, or risk ownership.',
  devops:
    'This term is sometimes reduced to automation, but it only helps when ownership, feedback, rollback, and operating discipline are clear.',
  cloud:
    'This term is sometimes treated as provider magic, but teams still own configuration, access, cost, resilience, and workload behavior.',
  networking:
    'This term is sometimes discussed as isolated plumbing, but network behavior depends on addressing, routing, policy, traffic patterns, and failure modes together.',
  data:
    'This term is sometimes treated as a storage choice, but useful data work also needs ownership, quality, lineage, governance, and consumers.',
  ai:
    'This term is sometimes described as model capability alone, but production value depends on data, evaluation, cost, safety, and integration.',
  syseng:
    'This term is sometimes treated as a one-time setup, but systems engineering usually requires lifecycle ownership, monitoring, limits, and recovery practice.',
  coding:
    'This term is sometimes treated as a style preference, but the practical test is whether it makes behavior easier to change, test, and operate.',
  integration:
    'This term is sometimes treated as connecting endpoints, but reliable integration also needs contracts, retries, ordering, ownership, and error handling.',
  agile:
    'This term is sometimes treated as ceremony, but it matters only when it improves decisions, flow, learning, or delivery outcomes.',
  governance:
    'This term is sometimes treated as paperwork, but governance should clarify risk decisions, control ownership, evidence, and accountability.',
  observability:
    'This term is sometimes treated as another dashboard, but it matters when it helps a team answer a production question and take action.',
  identity:
    'This term is sometimes blurred with adjacent access concepts, but strong identity programs separate proof of identity, policy, session state, and auditability.',
  architecture:
    'This term is sometimes used as abstract design language, but it should clarify constraints, trade-offs, ownership, and failure behavior.',
  appsec:
    'This term is sometimes treated as scanner output, but application security also depends on design choices, exploitability, remediation, and release controls.',
};

const relatedTerms: Record<Card['domain'], readonly string[]> = {
  cyber: ['Risk', 'Control', 'Threat Model', 'Incident Response'],
  devops: ['CI/CD', 'SRE', 'Automation', 'Release Management'],
  cloud: ['IAM', 'Networking', 'Resilience', 'FinOps'],
  networking: ['Routing', 'DNS', 'Firewall', 'Latency'],
  data: ['Lineage', 'Schema', 'Pipeline', 'Quality'],
  ai: ['Model', 'Evaluation', 'Inference', 'Data'],
  syseng: ['Reliability', 'Capacity', 'Runbook', 'Lifecycle'],
  coding: ['Testing', 'API', 'Refactoring', 'Maintainability'],
  integration: ['Contract', 'Queue', 'API', 'Retry'],
  agile: ['Backlog', 'Outcome', 'Flow', 'Feedback'],
  governance: ['Control', 'Policy', 'Audit', 'Risk'],
  observability: ['Metric', 'Trace', 'Log', 'SLO'],
  identity: ['Authentication', 'Authorization', 'Policy', 'Audit'],
  architecture: ['Trade-off', 'Boundary', 'Scalability', 'Resilience'],
  appsec: ['Threat Model', 'Vulnerability', 'Control', 'Remediation'],
};

const terms: Record<Card['domain'], readonly TermSeed[]> = {
  cyber: [
    ['Attack Surface Reduction', 'Removing exposed paths before they become incidents'],
    ['Security Control Validation', 'Testing whether defenses work as intended'],
    ['Breach and Attack Simulation', 'Automated exercises that test defensive coverage'],
    ['Purple Teaming', 'Joint attacker and defender improvement exercises'],
    ['Cyber Kill Chain', 'A staged model for understanding intrusions'],
    ['Tactics Techniques and Procedures', 'Reusable patterns used by adversaries'],
    ['Indicator of Compromise', 'Evidence that suspicious or malicious activity occurred'],
    ['Indicator of Attack', 'Behavior that suggests an attack is underway'],
    ['Command and Control', 'Attacker communication with compromised systems'],
    ['Lateral Movement', 'Moving from one compromised asset to another'],
    ['Privilege Escalation', 'Gaining higher permissions after initial access'],
    ['Credential Dumping', 'Extracting secrets from systems or memory'],
    ['Kerberoasting', 'Attacking service tickets in Active Directory'],
    ['Pass the Hash', 'Using password hashes as authentication material'],
    ['Security Baseline', 'A minimum expected configuration for systems'],
    ['Compensating Control', 'An alternate safeguard when the preferred control is not possible'],
    ['Control Effectiveness', 'How well a security control reduces real risk'],
    ['Security Exception', 'A documented and approved risk deviation'],
    ['Risk Acceptance', 'A decision to tolerate a known security risk'],
    ['Exposure Management', 'Prioritizing assets that are reachable and risky'],
    ['Asset Criticality', 'How important an asset is to business impact'],
    ['Security Orchestration Playbook', 'Automated response steps for common alerts'],
    ['Forensic Image', 'A preserved copy used for investigation evidence'],
    ['Chain of Custody', 'Documented handling of security evidence'],
    ['Malware Sandbox', 'An isolated environment for analyzing suspicious code'],
    ['YARA Rule', 'A pattern used to identify malware families or artifacts'],
    ['Sigma Rule', 'A portable detection rule for log events'],
    ['Deception Canary Token', 'A planted marker that alerts when touched'],
    ['Security Telemetry', 'Signals collected for detection and investigation'],
    ['Threat Hunting Hypothesis', 'A testable idea about adversary behavior in an environment'],
  ],
  devops: [
    ['Deployment Freeze', 'A planned pause on production changes'],
    ['Release Orchestration', 'Coordinating complex deployment steps and approvals'],
    ['Pipeline Template', 'A reusable CI/CD workflow pattern'],
    ['Build Provenance', 'Evidence about how an artifact was created'],
    ['Artifact Promotion', 'Moving a tested build through environments'],
    ['Environment Parity', 'Keeping environments similar enough for meaningful tests'],
    ['Configuration Drift Remediation', 'Correcting live state that differs from declared state'],
    ['Declarative Configuration', 'Describing desired state instead of procedural steps'],
    ['Controller Reconciliation', 'A loop that moves actual state toward desired state'],
    ['Kubernetes Admission Control', 'Policy checks before cluster objects are accepted'],
    ['Pod Disruption Budget', 'Limits on voluntary Kubernetes disruptions'],
    ['Horizontal Pod Autoscaler', 'Scaling pods based on workload signals'],
    ['Cluster Autoscaler', 'Adjusting cluster nodes to match workload demand'],
    ['Node Pool', 'A managed group of similar cluster nodes'],
    ['Sidecar Container', 'A helper container that supports the main workload'],
    ['Init Container', 'A setup container that runs before the application starts'],
    ['Blue-Green Cutover', 'Switching traffic between two complete versions'],
    ['Rollback Strategy', 'A planned path back to a known good release'],
    ['Release Health Check', 'A signal used to decide whether a release continues'],
    ['Synthetic Deployment Test', 'A scripted check run after deployment'],
    ['Operational Acceptance Test', 'A test that proves a service can be operated'],
    ['ChatOps', 'Running operational workflows from team chat'],
    ['Self-Service Provisioning', 'Letting teams request approved resources without tickets'],
    ['Golden Path Template', 'A recommended project or service starting point'],
    ['Service Scorecard', 'A measured view of service ownership and readiness'],
    ['Toil Budget', 'A limit on repetitive manual operational work'],
    ['Error Budget Policy', 'Rules that connect reliability budget to release decisions'],
    ['Runbook Linting', 'Checking operational procedures for completeness'],
    ['Incident Commander Role', 'The person coordinating response during an incident'],
    ['Change Failure Rate', 'The share of changes that cause degraded service'],
  ],
  cloud: [
    ['Account Vending Machine', 'Automated creation of governed cloud accounts'],
    ['Organization Unit', 'A cloud account grouping used for policy boundaries'],
    ['Service Control Policy', 'An organization-level permission guardrail'],
    ['Resource Policy', 'A policy attached directly to a cloud resource'],
    ['Permission Boundary', 'A maximum permission limit for identities'],
    ['Cross-Account Role', 'An assumed identity used across cloud accounts'],
    ['Cloud Audit Log', 'A record of administrative and service activity'],
    ['Cloud Trail Retention', 'Keeping cloud audit events for investigation'],
    ['Network Egress Control', 'Managing outbound traffic paths and cost'],
    ['NAT Gateway', 'Managed outbound internet access for private subnets'],
    ['Transit Gateway', 'A hub for connecting multiple cloud networks'],
    ['VPC Peering', 'Direct private connectivity between virtual networks'],
    ['Private Hosted Zone', 'DNS records resolvable only inside private networks'],
    ['Public Endpoint Exposure', 'A resource reachable from the public internet'],
    ['Instance Metadata Service', 'A local endpoint exposing workload metadata'],
    ['Ephemeral Storage', 'Temporary storage tied to compute lifecycle'],
    ['Provisioned IOPS', 'Reserved storage performance for predictable workloads'],
    ['Archive Storage Class', 'Low-cost storage for rarely accessed data'],
    ['Object Versioning', 'Keeping previous versions of stored objects'],
    ['Bucket Policy', 'Access rules attached to object storage buckets'],
    ['Server-Side Encryption', 'Provider-side encryption for stored data'],
    ['Envelope Encryption', 'Protecting data keys with a master key'],
    ['Cloud HSM', 'Dedicated hardware security modules in the cloud'],
    ['Regional Failover', 'Moving service traffic to another region'],
    ['Global Load Balancing', 'Routing users across regions or edges'],
    ['Edge Function', 'Code executed near users at CDN edge locations'],
    ['Cloud Scheduler', 'Managed execution of jobs on a schedule'],
    ['Managed Batch Service', 'Cloud orchestration for batch workloads'],
    ['Dedicated Host', 'Single-tenant physical capacity for workloads'],
    ['Sovereign Cloud', 'Cloud regions or services built for local control requirements'],
  ],
  networking: [
    ['ARP', 'Resolving local network addresses to hardware addresses'],
    ['Neighbor Discovery', 'IPv6 discovery for nearby routers and hosts'],
    ['ICMP', 'Control messages used for network diagnostics and errors'],
    ['Traceroute', 'Discovering the path packets take across networks'],
    ['Path MTU Discovery', 'Finding the largest packet size a path supports'],
    ['Jumbo Frames', 'Larger Ethernet frames used in controlled networks'],
    ['Spanning Tree Protocol', 'Preventing switching loops in layer two networks'],
    ['Link Aggregation', 'Combining links for capacity or redundancy'],
    ['VRRP', 'Providing a shared default gateway across routers'],
    ['HSRP', 'Cisco gateway redundancy for local networks'],
    ['ECMP', 'Routing traffic across equal-cost paths'],
    ['Route Redistribution', 'Sharing routes between routing protocols'],
    ['Prefix List', 'Filtering advertised or accepted network prefixes'],
    ['Access Control List', 'Traffic filtering rules on network devices'],
    ['Stateful Firewall', 'Filtering traffic using connection state'],
    ['Next-Generation Firewall', 'Firewall inspection with application awareness'],
    ['Intrusion Prevention System', 'Inline detection and blocking of malicious traffic'],
    ['Network Tap', 'A point for copying traffic for inspection'],
    ['SPAN Port', 'A switch mirror port for packet analysis'],
    ['NetFlow', 'Flow records that summarize network conversations'],
    ['sFlow', 'Sampled packet and flow telemetry'],
    ['Traffic Engineering', 'Steering network paths for performance or resilience'],
    ['WAN Optimization', 'Improving performance across wide area links'],
    ['DNS Forwarder', 'A resolver that passes queries to upstream servers'],
    ['Split-Horizon DNS', 'Different DNS answers based on requester location'],
    ['Recursive Resolver', 'A DNS server that performs lookups for clients'],
    ['Authoritative Name Server', 'A DNS server that owns records for a zone'],
    ['Anycast DNS', 'Serving the same DNS address from multiple locations'],
    ['Route Flap', 'Repeated route changes that destabilize networks'],
    ['Control Plane Policing', 'Protecting network device management processors'],
  ],
  data: [
    ['Data Lineage', 'Tracing data from source through transformations'],
    ['Column-Level Lineage', 'Tracking how individual fields are derived'],
    ['Data Profiling', 'Examining data shape, distribution, and anomalies'],
    ['Data Quality Rule', 'A machine-checkable expectation for data'],
    ['Data Freshness', 'How recently a dataset was updated'],
    ['Data Completeness', 'Whether required records and fields are present'],
    ['Data Deduplication', 'Removing duplicate records from datasets'],
    ['Entity Resolution', 'Matching records that refer to the same thing'],
    ['Reference Data', 'Shared lookup data used across systems'],
    ['Surrogate Key', 'A generated identifier used in data models'],
    ['Natural Key', 'A real-world identifier used as a key'],
    ['Primary Key', 'A field that uniquely identifies a row'],
    ['Foreign Key', 'A field that references another table'],
    ['Referential Integrity', 'Consistency between related data records'],
    ['Query Plan', 'The database strategy for executing a query'],
    ['Cost-Based Optimizer', 'A database component that chooses efficient query plans'],
    ['Vacuuming', 'Database cleanup that reclaims storage and maintains performance'],
    ['Write-Ahead Log', 'A durable log used before database changes are applied'],
    ['Point-in-Time Recovery', 'Restoring data to a specific moment'],
    ['Read Replica', 'A database copy used for read traffic or recovery'],
    ['Connection Pool', 'Reusable database connections shared by applications'],
    ['Data Skew', 'Uneven distribution that hurts processing performance'],
    ['Small Files Problem', 'Too many tiny files slowing distributed processing'],
    ['Compaction', 'Combining files or records for efficient storage'],
    ['Schema Drift', 'Unexpected source schema changes over time'],
    ['Schema Evolution', 'Planned changes to data structure'],
    ['Data Quarantine', 'Holding suspect records away from trusted outputs'],
    ['Data Reconciliation', 'Comparing datasets to confirm they agree'],
    ['Metric Store', 'A governed home for reusable business metrics'],
    ['Data Access Layer', 'A controlled interface for reading or writing data'],
  ],
  ai: [
    ['Attention Mechanism', 'A model technique for weighting relevant context'],
    ['Self-Attention', 'Attention applied within one sequence of tokens'],
    ['Positional Encoding', 'Information that tells a model token order'],
    ['System Prompt', 'Instructions that shape model behavior'],
    ['Few-Shot Prompting', 'Providing examples inside a prompt'],
    ['Chain-of-Thought Prompting', 'Prompting that encourages intermediate reasoning'],
    ['Prompt Template', 'A reusable structure for model instructions'],
    ['Context Retrieval', 'Selecting external information for a model call'],
    ['Reranker', 'A model that reorders retrieved results by relevance'],
    ['Hybrid Search', 'Combining keyword and vector retrieval'],
    ['Embedding Model', 'A model that converts content into vectors'],
    ['Chunking Strategy', 'Splitting documents for retrieval and context'],
    ['Grounding', 'Connecting model output to source evidence'],
    ['Citation Generation', 'Linking generated answers back to sources'],
    ['Model Context Protocol Server', 'A tool server exposed to AI clients'],
    ['Tool Calling Schema', 'A structured contract for model tool use'],
    ['Agent Memory', 'Stored context reused across AI interactions'],
    ['Human-in-the-Loop Review', 'A person checking or approving AI output'],
    ['Eval Dataset', 'Examples used to measure AI behavior'],
    ['Golden Answer Set', 'Expected outputs used for evaluation'],
    ['LLM Judge', 'A model used to grade model outputs'],
    ['Safety Classifier', 'A model that detects unsafe content or behavior'],
    ['Model Drift', 'Behavior change over time or across model versions'],
    ['Inference Latency', 'Time required to produce a model response'],
    ['Batch Inference', 'Running predictions for many inputs at once'],
    ['Streaming Response', 'Returning model output incrementally'],
    ['Token Budget', 'The available input and output capacity for a model call'],
    ['Prompt Injection Defense', 'Controls that reduce malicious instruction influence'],
    ['Model Routing', 'Choosing a model based on task, cost, or risk'],
    ['AI Observability', 'Telemetry for prompts, outputs, cost, and quality'],
  ],
  syseng: [
    ['CPU Scheduling', 'How an operating system assigns processor time'],
    ['NUMA', 'Memory architecture where access speed depends on locality'],
    ['Page Cache', 'Memory used by the OS to cache filesystem data'],
    ['Swap Space', 'Disk-backed memory used under pressure'],
    ['OOM Killer', 'A Linux mechanism that terminates processes under memory exhaustion'],
    ['File Descriptor', 'An OS handle for files, sockets, and streams'],
    ['Inode', 'Filesystem metadata for files and directories'],
    ['Mount Point', 'A directory where a filesystem is attached'],
    ['Bind Mount', 'Mounting one filesystem path at another path'],
    ['Overlay Filesystem', 'Layered filesystem behavior used by containers'],
    ['Kernel Module', 'Loadable code that extends kernel functionality'],
    ['Device Driver', 'Software that lets the OS communicate with hardware'],
    ['System Call', 'A controlled request from user space into the kernel'],
    ['Daemon Process', 'A background process that provides a service'],
    ['Process Supervisor', 'A system that starts and restarts services'],
    ['Core Dump', 'A captured process memory image after a crash'],
    ['CrashLoop', 'Repeated service crashes and restarts'],
    ['Health Check Endpoint', 'A service endpoint used to judge process health'],
    ['Graceful Shutdown', 'Stopping a service while completing in-flight work'],
    ['Log Rotation', 'Managing log file size and retention on hosts'],
    ['Time Drift', 'Clock mismatch between systems'],
    ['Certificate Chain', 'The trust path from a certificate to a root authority'],
    ['Keytab', 'A Kerberos file containing service credentials'],
    ['LDAP Directory', 'A directory service for users, groups, and systems'],
    ['Bare Metal Server', 'A physical machine dedicated to workloads'],
    ['Rack Awareness', 'Designing placement around physical failure domains'],
    ['Power Redundancy', 'Duplicate power paths for infrastructure'],
    ['Firmware Update', 'Updating low-level device software'],
    ['Hardware Lifecycle', 'Planning purchase, support, refresh, and retirement'],
    ['Remote Console', 'Out-of-band access for server management'],
  ],
  coding: [
    ['Unit Test', 'A focused test of one small behavior'],
    ['Integration Test', 'A test across real component boundaries'],
    ['End-to-End Test', 'A test of a complete user or system flow'],
    ['Test Fixture', 'Reusable setup data for tests'],
    ['Test Double', 'A substitute used during testing'],
    ['Mock Object', 'A test double that verifies interactions'],
    ['Property-Based Testing', 'Testing behavior across generated inputs'],
    ['Mutation Testing', 'Changing code to see whether tests catch defects'],
    ['Snapshot Test', 'Comparing output to a stored reference'],
    ['Code Coverage', 'How much code is exercised by tests'],
    ['Cyclomatic Complexity', 'A measure of branching paths through code'],
    ['Cohesion', 'How closely responsibilities in a module belong together'],
    ['Coupling', 'How strongly one module depends on another'],
    ['Encapsulation', 'Hiding internal details behind a stable interface'],
    ['Immutability', 'Keeping values from changing after creation'],
    ['Pure Function', 'A function with no side effects and deterministic output'],
    ['Side Effect', 'A change outside a function return value'],
    ['Null Safety', 'Preventing missing values from causing runtime failures'],
    ['Generics', 'Type parameters that make code reusable'],
    ['Interface Segregation', 'Keeping interfaces small and client-specific'],
    ['Adapter Pattern', 'Translating one interface into another'],
    ['Factory Pattern', 'Centralizing object creation decisions'],
    ['Repository Pattern', 'Abstracting data access behind an interface'],
    ['Unit of Work', 'Grouping changes into one commit boundary'],
    ['Optimistic Locking', 'Detecting conflicting writes without holding locks'],
    ['Pessimistic Locking', 'Preventing conflicts by taking locks first'],
    ['Memory Leak', 'Retained memory that is no longer useful'],
    ['Race Condition', 'A defect caused by timing between concurrent operations'],
    ['Thread Pool', 'A reusable group of worker threads'],
    ['Serialization', 'Converting data into a transport or storage format'],
  ],
  integration: [
    ['API Contract', 'An agreed request and response shape between systems'],
    ['Backward-Compatible Change', 'An interface change that existing clients can tolerate'],
    ['Breaking Change', 'A change that existing consumers cannot use safely'],
    ['Deprecation Policy', 'Rules for retiring old interfaces'],
    ['Consumer Registration', 'Tracking which systems use an interface'],
    ['Producer Service', 'A system that emits data or events'],
    ['Consumer Service', 'A system that receives data or events'],
    ['Message Envelope', 'Metadata wrapped around a message payload'],
    ['Message Header', 'Routing or context metadata carried with a message'],
    ['Correlation Header', 'A header used to connect related requests or events'],
    ['Request Reply Pattern', 'A synchronous interaction over messaging'],
    ['Publish Subscribe Pattern', 'One producer sending events to many consumers'],
    ['Competing Consumers', 'Multiple workers sharing a queue of work'],
    ['Poison Message', 'A message that repeatedly fails processing'],
    ['Retry Policy', 'Rules for retrying failed integration calls'],
    ['Timeout Policy', 'A limit on how long a call may wait'],
    ['Schema Compatibility', 'Whether old and new message schemas can coexist'],
    ['Event Versioning', 'Changing event formats without breaking consumers'],
    ['Payload Transformation', 'Converting data between formats or models'],
    ['Protocol Translation', 'Bridging systems that use different protocols'],
    ['Adapter Service', 'A service that hides an external system interface'],
    ['Anti-Corruption Layer', 'A boundary that protects a domain model from outside concepts'],
    ['Batch Interface', 'A scheduled file or bulk data exchange'],
    ['File Drop Integration', 'A system handoff using shared files'],
    ['Managed File Transfer', 'Controlled movement of files between organizations'],
    ['API Throttling', 'Slowing callers to protect a service'],
    ['Webhook Signature', 'A signature that proves webhook authenticity'],
    ['Replay Protection', 'Controls that stop old messages from being accepted again'],
    ['Idempotent Consumer', 'A consumer that handles duplicate messages safely'],
    ['Exactly-Once Claim', 'A reliability promise that needs careful scrutiny'],
  ],
  agile: [
    ['Product Discovery', 'Learning what problem is worth solving'],
    ['Opportunity Solution Tree', 'Mapping opportunities to possible solutions'],
    ['Assumption Mapping', 'Finding risky assumptions behind product decisions'],
    ['Experiment Design', 'Planning a test that can change a decision'],
    ['Outcome Metric', 'A measurement tied to customer or business result'],
    ['Input Metric', 'A controllable activity that influences outcomes'],
    ['Leading Indicator', 'An early signal of future performance'],
    ['Lagging Indicator', 'A result visible after the fact'],
    ['Decision Log', 'A record of important product or delivery decisions'],
    ['Stakeholder Map', 'A view of people affected by or influencing work'],
    ['Dependency Map', 'A view of teams or systems that work depends on'],
    ['Delivery Forecast', 'A probabilistic estimate of completion timing'],
    ['Monte Carlo Forecast', 'A forecast using historical throughput simulation'],
    ['Throughput', 'The amount of work finished in a period'],
    ['Work Item Aging', 'How long active work has been in progress'],
    ['Blocked Work', 'Work that cannot progress without outside action'],
    ['Expedite Lane', 'A flow path for urgent work'],
    ['Class of Service', 'A policy for handling different types of work'],
    ['Service Level Expectation', 'A forecast of normal delivery time'],
    ['Flow Debt', 'Accumulated delay from too much work in progress'],
    ['Team API', 'A clear description of how other teams interact with a team'],
    ['Enabling Team', 'A team that helps others build new capabilities'],
    ['Stream-Aligned Team', 'A team organized around a flow of value'],
    ['Complicated Subsystem Team', 'A team responsible for specialized system knowledge'],
    ['Platform Team', 'A team that provides internal capabilities as a product'],
    ['RACI Matrix', 'A responsibility model for roles in a decision or activity'],
    ['DACI Framework', 'A decision model with driver, approver, contributors, and informed'],
    ['Product Bet', 'A deliberate investment based on uncertainty and expected payoff'],
    ['Discovery Backlog', 'A list of questions or assumptions to investigate'],
    ['Delivery Cadence', 'The rhythm at which work is planned, reviewed, and shipped'],
  ],
  governance: [
    ['Control Framework', 'A structured set of controls for managing risk'],
    ['Control Library', 'A reusable catalog of control definitions'],
    ['Control Testing', 'Checking whether a control operated effectively'],
    ['Control Deficiency', 'A weakness found in control design or operation'],
    ['Corrective Action Plan', 'A tracked plan to remediate a finding'],
    ['Management Response', 'An owner response to an audit or risk finding'],
    ['Internal Audit', 'Independent review of controls and risk management'],
    ['External Audit', 'Third-party assurance over controls or statements'],
    ['Audit Scope', 'The systems, processes, and periods included in review'],
    ['Evidence Request List', 'A list of proof items requested by auditors'],
    ['Policy Lifecycle', 'Creating, approving, reviewing, and retiring policies'],
    ['Standard', 'A mandatory detailed requirement that supports policy'],
    ['Procedure', 'Step-by-step instructions for performing required work'],
    ['Guideline', 'Recommended practice that supports consistent decisions'],
    ['Risk Treatment', 'The chosen response to an identified risk'],
    ['Risk Mitigation', 'Reducing the likelihood or impact of risk'],
    ['Risk Transfer', 'Moving some risk through insurance or contract terms'],
    ['Residual Risk', 'Risk remaining after controls are applied'],
    ['Inherent Risk', 'Risk before controls are considered'],
    ['Key Risk Indicator', 'A metric that warns risk is increasing'],
    ['Key Performance Indicator', 'A metric that tracks operational performance'],
    ['Regulatory Change Management', 'Tracking new obligations and updating controls'],
    ['Data Processing Agreement', 'Contract terms for personal data handling'],
    ['Subprocessor Register', 'A list of vendors processing data on behalf of a service'],
    ['Records Disposition', 'Approved disposal of records after retention ends'],
    ['Legal Hold', 'Preserving records because of litigation or investigation'],
    ['Exception Expiration', 'The date an approved policy exception must be reviewed'],
    ['Third-Party Due Diligence', 'Review before entering a vendor relationship'],
    ['Fourth-Party Risk', 'Risk from a vendor own suppliers'],
    ['Operational Resilience', 'Ability to continue important services through disruption'],
  ],
  observability: [
    ['Trace Sampling Rate', 'The share of traces kept for analysis'],
    ['Tail-Based Sampling', 'Choosing traces to keep after seeing request outcome'],
    ['Head-Based Sampling', 'Choosing traces to keep at request start'],
    ['Log Sampling', 'Reducing log volume while preserving useful evidence'],
    ['Metric Cardinality Budget', 'Limits on unique metric label combinations'],
    ['Exemplar', 'A trace reference attached to a metric point'],
    ['Span Attribute', 'Metadata that describes a traced operation'],
    ['Resource Attribute', 'Telemetry metadata about the emitting service or host'],
    ['Baggage', 'Context propagated across service calls'],
    ['Collector Pipeline', 'Telemetry processing inside an observability collector'],
    ['Exporter', 'A component that sends telemetry to a backend'],
    ['Receiver', 'A component that accepts telemetry from applications'],
    ['Processor', 'A component that transforms telemetry in transit'],
    ['Log Enrichment', 'Adding context that makes logs easier to query'],
    ['Trace Waterfall', 'A visual timeline of spans in a request'],
    ['Service Dependency Graph', 'A map of calls between services'],
    ['Alert Deduplication', 'Combining repeated alerts into fewer notifications'],
    ['Alert Suppression', 'Temporarily muting expected or dependent alerts'],
    ['Alert Routing', 'Sending notifications to the right team or workflow'],
    ['Notification Fatigue', 'Reduced response quality from too many alerts'],
    ['Incident Timeline', 'A chronological record of detection and response'],
    ['Change Event', 'A deployment or configuration change shown in telemetry'],
    ['Deployment Marker', 'A marker that ties telemetry to a release'],
    ['Error Grouping', 'Combining similar errors into actionable groups'],
    ['Stack Trace', 'A call path captured when code fails'],
    ['Core Web Vitals', 'User experience metrics for web performance'],
    ['Availability SLI', 'A measurement of successful service availability'],
    ['Latency SLI', 'A measurement of service response time'],
    ['Freshness SLO', 'A target for how current data must be'],
    ['Observability Maturity Model', 'A staged view of telemetry and response capability'],
  ],
  identity: [
    ['Adaptive Authentication', 'Changing authentication requirements based on risk'],
    ['Step-Up Authentication', 'Requesting stronger proof for sensitive actions'],
    ['Session Binding', 'Tying a session to device or cryptographic context'],
    ['Session Timeout', 'A limit on how long a session remains valid'],
    ['Token Exchange', 'Trading one token for another under policy'],
    ['Token Introspection', 'Checking token state with an authorization server'],
    ['Token Binding', 'Constraining token use to a specific holder or channel'],
    ['Proof of Possession Token', 'A token requiring proof of key ownership'],
    ['Device Code Flow', 'OAuth flow for devices with limited input'],
    ['Client Credentials Flow', 'OAuth flow for machine-to-machine access'],
    ['Authorization Code Flow', 'OAuth flow for user sign-in through a browser'],
    ['PKCE', 'Protection for OAuth authorization code interception'],
    ['Redirect URI', 'The allowed callback location after authentication'],
    ['Consent Screen', 'A user approval step for delegated access'],
    ['Delegated Authorization', 'Granting an app limited access on a user behalf'],
    ['Directory Synchronization', 'Keeping identities consistent across directories'],
    ['Group Nesting', 'Using groups inside other groups for access policy'],
    ['Entitlement', 'A specific granted permission or access right'],
    ['Access Certification', 'A formal review and approval of access'],
    ['Identity Proofing', 'Verifying a real-world person before account issuance'],
    ['Account Recovery', 'Restoring access after lost credentials or lockout'],
    ['Dormant Account', 'An unused account that may create risk'],
    ['Orphaned Account', 'An account without a valid owner'],
    ['Shared Account', 'An account used by multiple people or processes'],
    ['Service Principal', 'An application identity used for automation'],
    ['Managed Service Account', 'A service account with managed credential rotation'],
    ['Federation Metadata', 'Configuration that lets identity systems trust each other'],
    ['Claims Mapping', 'Transforming identity claims between systems'],
    ['Policy Decision Point', 'A component that evaluates access policy'],
    ['Policy Enforcement Point', 'A component that applies an access decision'],
  ],
  architecture: [
    ['Domain Boundary', 'A separation around business capability and ownership'],
    ['Integration Boundary', 'A contract where systems exchange data or commands'],
    ['Deployment Unit', 'A component released as one operational unit'],
    ['Runtime Topology', 'How components are arranged while running'],
    ['Control Plane', 'The management layer that configures system behavior'],
    ['Data Plane', 'The path where user or workload traffic flows'],
    ['Management Plane', 'Administrative interfaces used to operate a system'],
    ['Sidecar Pattern', 'A helper process deployed beside an application'],
    ['Ambassador Pattern', 'A proxy that handles communication for an application'],
    ['Backend for Frontend', 'A tailored backend API for a specific client experience'],
    ['Aggregator Pattern', 'A service that combines responses from multiple sources'],
    ['Fan-Out Fan-In', 'Parallel calls whose results are gathered back together'],
    ['CQRS Read Model', 'A query-optimized model separated from writes'],
    ['Materialized Projection', 'A precomputed view built from source events or data'],
    ['Saga Orchestration', 'A coordinator controlling a distributed transaction workflow'],
    ['Saga Choreography', 'Services coordinating a workflow through events'],
    ['Transactional Boundary', 'The scope where consistency is guaranteed'],
    ['Consistency Boundary', 'The part of a system that must agree at one time'],
    ['Read-After-Write Consistency', 'Guarantee that a client can read its own write'],
    ['Quorum', 'The minimum replicas needed to accept or confirm an operation'],
    ['Leader Election', 'Choosing one node to coordinate a distributed task'],
    ['Split Brain', 'Two nodes believing they are primary at the same time'],
    ['Gossip Protocol', 'Nodes spreading state by peer-to-peer exchange'],
    ['Service Decomposition', 'Breaking a system into independently owned services'],
    ['Architectural Fitness Function', 'An automated check for an architecture quality'],
    ['Evolutionary Architecture', 'Architecture designed to change through guided feedback'],
    ['Reference Architecture', 'A reusable architecture pattern for common needs'],
    ['Architecture Runway', 'Technical foundation that enables upcoming delivery'],
    ['Decision Reversal Cost', 'How hard it is to change a design choice later'],
    ['Platform Capability', 'A reusable internal service that product teams build on'],
  ],
  appsec: [
    ['Secure Defaults', 'Settings that start in the safest practical state'],
    ['Fail Closed', 'Denying access when a security check cannot complete'],
    ['Least Privilege by Default', 'Starting identities with minimal permissions'],
    ['Input Canonicalization', 'Normalizing input before validation or comparison'],
    ['Allowlist Validation', 'Accepting only known-good input patterns'],
    ['Contextual Output Encoding', 'Encoding output for the exact destination context'],
    ['HTML Sanitization', 'Removing unsafe markup while preserving allowed content'],
    ['Template Injection', 'Executing attacker input through a template engine'],
    ['Mass Assignment', 'Unexpected fields changing protected application state'],
    ['Insecure Direct Object Reference', 'Accessing objects without proper authorization checks'],
    ['Broken Object Property Level Authorization', 'Unauthorized access to object fields'],
    ['Cross-Origin Resource Sharing', 'Browser policy for cross-origin API access'],
    ['Preflight Request', 'Browser check before certain cross-origin requests'],
    ['SameSite Cookie', 'Cookie behavior that limits cross-site sending'],
    ['CSRF Token', 'A token that proves a browser request came from the intended flow'],
    ['Password Hashing', 'One-way protection for stored passwords'],
    ['Salt', 'Random data added before password hashing'],
    ['Pepper', 'A secret added to password hashing outside the database'],
    ['Key Derivation Function', 'A function designed to produce keys from secrets'],
    ['Nonce', 'A value used once in cryptographic operations'],
    ['Replay Attack', 'Reusing a valid request or message maliciously'],
    ['Security Regression Test', 'A test that proves a fixed flaw stays fixed'],
    ['Abuse Case Testing', 'Testing how a feature can be misused'],
    ['Threat Model Review', 'Reviewing attack paths before implementation'],
    ['Security Acceptance Criteria', 'Security-specific conditions for completing work'],
    ['Dependency Review', 'Assessing third-party package risk before use'],
    ['License Compliance', 'Ensuring dependency licenses are acceptable'],
    ['Build Tampering', 'Unauthorized changes in the build or packaging process'],
    ['Secret Rotation', 'Replacing credentials on a planned or emergency basis'],
    ['Security Exception Review', 'Reassessing an accepted application security risk'],
  ],
};

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function difficultyForIndex(index: number): Card['difficulty'] {
  if (index < 10) {
    return 'beginner';
  }

  if (index < 22) {
    return 'intermediate';
  }

  return 'advanced';
}

export const deepExpansionCards: Card[] = Object.entries(terms).flatMap(
  ([domain, domainTerms]) =>
    domainTerms.map(([title, subtitle], index) => {
      const typedDomain = domain as Card['domain'];
      const label = domainLabels[typedDomain];

      return {
        id: `deep-${typedDomain}-${slugify(title)}`,
        domain: typedDomain,
        title,
        subtitle,
        difficulty: difficultyForIndex(index),
        tags: [...domainTags[typedDomain]],
        definition: `${title} is a ${label} term focused on ${subtitle.toLowerCase()}.`,
        whyItMatters: `It gives teams a precise way to discuss ${subtitle.toLowerCase()} without collapsing the issue into vague ${label} language.`,
        analogy:
          'Like adding a labeled control to a complex console: the term is useful because it points everyone to the same lever, signal, or decision.',
        soundsSmartToSay: `"For ${title}, I would clarify the owner, the operating boundary, and the evidence that tells us it is working."`,
        commonConfusions: [domainConfusions[typedDomain]],
        relatedTerms: [...relatedTerms[typedDomain]],
      };
    }),
);
