import type { Card } from '../types';

type MeetingPrepDomain = Extract<
  Card['domain'],
  'observability' | 'identity' | 'architecture' | 'appsec'
>;

type Seed = readonly [
  slug: string,
  title: string,
  subtitle: string,
  difficulty: Card['difficulty'],
  definition: string,
  meetingCue: string,
  relatedTerms: string[],
];

const domainCopy: Record<
  MeetingPrepDomain,
  { analogy: string; tag: string; confusion: string; context: string }
> = {
  observability: {
    analogy:
      'Like a control room: signals, logs, and timelines matter because operators need enough context to make decisions while pressure is high.',
    tag: 'reliability',
    confusion:
      'Observability is not more dashboards by itself. The signal has to answer a decision the team needs to make.',
    context: 'reliability or incident',
  },
  identity: {
    analogy:
      'Like a secure building: identity proves who is at the door, policy decides which rooms they may enter, and logs show what happened.',
    tag: 'identity',
    confusion:
      'Authentication proves identity; authorization grants permissions. Meeting prep should separate those questions.',
    context: 'access or trust',
  },
  architecture: {
    analogy:
      'Like a city plan: roads, utilities, zones, and emergency routes only make sense when demand and trade-offs are explicit.',
    tag: 'system design',
    confusion:
      'Architecture vocabulary is useful only when it clarifies constraints, ownership, trade-offs, and failure behavior.',
    context: 'design review',
  },
  appsec: {
    analogy:
      'Like reviewing a delivery chain: the design, code, dependencies, pipeline, and runtime all need security checks at the right point.',
    tag: 'application security',
    confusion:
      'Security tooling finds evidence and risk. It does not replace secure design choices or accountable remediation.',
    context: 'security review',
  },
};

function buildCards(domain: MeetingPrepDomain, seeds: readonly Seed[]): Card[] {
  const copy = domainCopy[domain];

  return seeds.map(
    ([slug, title, subtitle, difficulty, definition, meetingCue, relatedTerms]) => ({
      id: `${domain}-${slug}`,
      domain,
      title,
      subtitle,
      difficulty,
      tags: [copy.tag, 'meeting prep', difficulty],
      definition,
      whyItMatters: `In a ${copy.context} meeting, ${meetingCue}`,
      analogy: copy.analogy,
      soundsSmartToSay: `"${meetingCue}"`,
      commonConfusions: [copy.confusion],
      relatedTerms,
    }),
  );
}

const observabilitySeeds: Seed[] = [
  [
    'telemetry',
    'Telemetry',
    'Signals emitted by a running system',
    'beginner',
    'Telemetry is the metrics, logs, traces, events, and metadata a system emits so people and tools can understand its behavior.',
    'start by asking which signal will show whether users are healthy after the change.',
    ['Metrics', 'Logs', 'Traces', 'Instrumentation'],
  ],
  [
    'metrics',
    'Metrics',
    'Numeric measurements over time',
    'beginner',
    'Metrics are time-series measurements such as request count, error rate, queue depth, memory use, or latency percentiles.',
    'clarify which metrics are leading indicators and which prove user impact.',
    ['Time Series', 'SLI', 'Dashboard', 'Alert'],
  ],
  [
    'logs',
    'Logs',
    'Discrete records of events and context',
    'beginner',
    'Logs capture event details such as errors, state transitions, request metadata, and diagnostic context.',
    'ask whether the logs carry enough context to debug the failure without exposing sensitive data.',
    ['Structured Logging', 'Correlation ID', 'Retention', 'Redaction'],
  ],
  [
    'traces',
    'Distributed Traces',
    'Request timelines across services',
    'beginner',
    'A distributed trace follows one request through services and records spans that show where work and time were spent.',
    'use traces when the question is where latency or failure moved across service boundaries.',
    ['Span', 'Trace Context', 'OpenTelemetry', 'Service Map'],
  ],
  [
    'span',
    'Span',
    'One timed operation inside a trace',
    'beginner',
    'A span represents a timed unit of work such as an HTTP handler, database query, queue publish, or downstream API call.',
    'ask which spans identify the slow dependency rather than treating the whole request as one black box.',
    ['Trace', 'Attribute', 'Parent Span', 'Latency'],
  ],
  [
    'trace-context',
    'Trace Context',
    'Metadata that connects spans together',
    'intermediate',
    'Trace context carries identifiers across service calls so telemetry from one request can be stitched into a distributed trace.',
    'check whether context propagation survives queues, jobs, and third-party calls.',
    ['W3C Trace Context', 'Correlation ID', 'Span', 'Propagation'],
  ],
  [
    'correlation-id',
    'Correlation ID',
    'A shared identifier for related events',
    'beginner',
    'A correlation ID ties logs, requests, jobs, and downstream activity to the same business operation.',
    'ask for a correlation ID path before promising the team can investigate cross-service failures quickly.',
    ['Request ID', 'Trace ID', 'Logging', 'Support'],
  ],
  [
    'structured-logging',
    'Structured Logging',
    'Logs with queryable fields',
    'beginner',
    'Structured logs store fields such as user ID, order ID, severity, and error code instead of relying only on free text.',
    'prefer queryable fields over parsing prose when the team expects incident search and alerting.',
    ['JSON Log', 'Log Query', 'Schema', 'Redaction'],
  ],
  [
    'high-cardinality',
    'High-Cardinality Data',
    'Many distinct telemetry values',
    'intermediate',
    'High-cardinality telemetry has many unique values, such as user IDs or request IDs, which can be powerful for debugging and expensive for metrics stores.',
    'separate values needed for drill-down from labels that will explode metric cost.',
    ['Label', 'Attribute', 'Metrics Cost', 'Trace'],
  ],
  [
    'sampling',
    'Telemetry Sampling',
    'Keeping a useful subset of signals',
    'intermediate',
    'Sampling stores only part of high-volume telemetry, often based on probability, errors, latency, or tail decisions.',
    'ask what evidence could disappear when telemetry volume is reduced.',
    ['Head Sampling', 'Tail Sampling', 'Trace', 'Cost Control'],
  ],
  [
    'sli',
    'Service Level Indicator',
    'A measurement of service behavior',
    'beginner',
    'An SLI is a measured indicator of service behavior such as success rate, latency, freshness, or availability.',
    'name the SLI before debating a reliability target.',
    ['SLO', 'SLA', 'Availability', 'Latency'],
  ],
  [
    'slo',
    'Service Level Objective',
    'A reliability target for an SLI',
    'beginner',
    'An SLO sets a target for an SLI over a window, such as 99.9 percent successful checkout requests in 30 days.',
    'ask whether the proposed target reflects user need or an arbitrary uptime number.',
    ['SLI', 'Error Budget', 'SLA', 'Burn Rate'],
  ],
  [
    'sla',
    'Service Level Agreement',
    'An external reliability promise',
    'beginner',
    'An SLA is a contractual or customer-facing commitment, usually with consequences when the promise is missed.',
    'separate the customer promise from the internal objective used to manage engineering risk.',
    ['SLO', 'Contract', 'Support', 'Availability'],
  ],
  [
    'error-budget',
    'Error Budget',
    'Allowed unreliability inside an SLO',
    'intermediate',
    'An error budget is the amount of failure or unavailability a service can spend while still meeting its SLO.',
    'frame release speed against remaining error budget instead of arguing stability in the abstract.',
    ['SLO', 'Burn Rate', 'Change Freeze', 'Reliability'],
  ],
  [
    'burn-rate',
    'Error Budget Burn Rate',
    'How quickly reliability budget is consumed',
    'intermediate',
    'Burn rate compares current bad events to the rate that would exhaust the error budget over the SLO window.',
    'ask whether the alert catches fast user harm and slow budget drain separately.',
    ['Multiwindow Alert', 'SLO', 'Alert', 'Incident'],
  ],
  [
    'alert-threshold',
    'Alert Threshold',
    'The condition that triggers attention',
    'beginner',
    'An alert threshold defines when a signal becomes important enough to notify people or automation.',
    'ask what action follows the threshold before adding another page.',
    ['Paging', 'Warning Alert', 'Noise', 'Runbook'],
  ],
  [
    'symptom-alert',
    'Symptom Alert',
    'Alerting on user-visible trouble',
    'intermediate',
    'A symptom alert fires on outcomes users feel, such as elevated failed checkouts, instead of every internal cause.',
    'lead with symptoms for pages and keep cause signals for diagnosis.',
    ['Cause Alert', 'SLI', 'Golden Signals', 'Pager'],
  ],
  [
    'paging-policy',
    'Paging Policy',
    'Rules for interrupting responders',
    'beginner',
    'A paging policy defines which alerts wake people, who receives them, and how escalation works.',
    'treat an interrupting page as a promise that human action is needed now.',
    ['On-Call', 'Escalation', 'Severity', 'Alert Fatigue'],
  ],
  [
    'dashboard',
    'Operational Dashboard',
    'A view that supports a decision',
    'beginner',
    'An operational dashboard groups signals that help a team understand service state and make a specific decision.',
    'ask which decision the dashboard supports before adding charts.',
    ['Metrics', 'Incident', 'Golden Signals', 'Drill-Down'],
  ],
  [
    'golden-signals',
    'Golden Signals',
    'Latency, traffic, errors, and saturation',
    'beginner',
    'Golden signals are a compact starting set for service health: latency, traffic, errors, and saturation.',
    'use golden signals to orient the room before drilling into component detail.',
    ['Latency', 'Traffic', 'Errors', 'Saturation'],
  ],
  [
    'red-method',
    'RED Method',
    'Rate, errors, and duration for services',
    'beginner',
    'RED measures request rate, error count, and duration for request-driven services.',
    'use RED when the system is a service handling requests and the team needs an immediate health frame.',
    ['Golden Signals', 'Latency', 'HTTP', 'Dashboard'],
  ],
  [
    'use-method',
    'USE Method',
    'Utilization, saturation, and errors for resources',
    'intermediate',
    'USE checks utilization, saturation, and errors for resources such as CPU, memory, disks, and network links.',
    'switch to USE when the suspected bottleneck is a resource rather than a request path.',
    ['Resource', 'Saturation', 'Capacity', 'Performance'],
  ],
  [
    'apdex',
    'Apdex',
    'A satisfaction score for response time',
    'intermediate',
    'Apdex summarizes response time experience against satisfied and tolerated latency thresholds.',
    'check whether one score hides a tail latency problem important users still feel.',
    ['Latency', 'Threshold', 'User Experience', 'Percentile'],
  ],
  [
    'latency-percentile',
    'Latency Percentile',
    'Tail behavior instead of averages',
    'beginner',
    'Latency percentiles show the response time below which a percentage of requests completed, such as p95 or p99.',
    'ask for p95 or p99 when averages mask the slow requests that drive complaints.',
    ['p95', 'p99', 'Histogram', 'Tail Latency'],
  ],
  [
    'saturation',
    'Saturation',
    'How close a resource is to its limit',
    'beginner',
    'Saturation describes queued work or exhausted capacity when demand approaches a resource limit.',
    'find the saturating resource before recommending scale-out.',
    ['Queue Depth', 'CPU', 'Connection Pool', 'Backpressure'],
  ],
  [
    'capacity-headroom',
    'Capacity Headroom',
    'Spare room before service limits',
    'intermediate',
    'Capacity headroom is the margin between current demand and the point where resources or quotas degrade service.',
    'ask how much headroom remains for peak demand and failure scenarios.',
    ['Autoscaling', 'Quota', 'Saturation', 'Load Test'],
  ],
  [
    'synthetic-monitoring',
    'Synthetic Monitoring',
    'Scripted checks from controlled probes',
    'beginner',
    'Synthetic monitoring runs scripted requests or user journeys to test service behavior from known locations.',
    'use synthetic checks to catch broken paths before waiting for user traffic.',
    ['Uptime Check', 'RUM', 'Probe', 'Journey'],
  ],
  [
    'real-user-monitoring',
    'Real User Monitoring',
    'Measuring real client experience',
    'beginner',
    'Real User Monitoring captures performance and errors from actual user browsers or apps.',
    'compare real user data with lab probes when geography and device mix matter.',
    ['Frontend', 'Synthetic Monitoring', 'Web Vitals', 'Session'],
  ],
  [
    'uptime-check',
    'Uptime Check',
    'A simple reachability probe',
    'beginner',
    'An uptime check periodically verifies that an endpoint responds from selected locations.',
    'treat uptime as the floor and ask what deeper transaction proves the service works.',
    ['Synthetic Monitoring', 'Health Check', 'Availability', 'Probe'],
  ],
  [
    'heartbeat',
    'Heartbeat Signal',
    'Evidence a job or agent is still alive',
    'beginner',
    'A heartbeat is a periodic signal that a process, job, device, or integration is still running as expected.',
    'ask for a heartbeat when silence itself should be treated as failure.',
    ['Cron', 'Freshness', 'Alert', 'Liveness'],
  ],
  [
    'incident-severity',
    'Incident Severity',
    'A scale for urgency and impact',
    'beginner',
    'Incident severity categorizes impact so responders align on urgency, communication, and escalation.',
    'state user impact and severity early so the response process matches the problem.',
    ['SEV', 'Escalation', 'Status Page', 'Incident Commander'],
  ],
  [
    'on-call-rotation',
    'On-Call Rotation',
    'Who responds when services need attention',
    'beginner',
    'An on-call rotation schedules responders for urgent operational issues outside ordinary work flow.',
    'ask whether ownership and escalation are explicit before relying on an alert path.',
    ['Pager', 'Escalation', 'Runbook', 'Service Ownership'],
  ],
  [
    'escalation-policy',
    'Escalation Policy',
    'A fallback path when response stalls',
    'beginner',
    'An escalation policy sends an incident to additional responders or leaders if the first owner does not respond.',
    'confirm escalation timing for high-impact paths instead of assuming the page reaches the right person.',
    ['On-Call', 'Severity', 'Pager', 'Incident'],
  ],
  [
    'runbook',
    'Runbook',
    'Steps for a repeatable operational task',
    'beginner',
    'A runbook documents diagnosis, commands, safety checks, communication, and rollback for a known operational task.',
    'ask for a runbook when the response should be repeatable at 3 AM.',
    ['Playbook', 'Automation', 'Incident', 'Rollback'],
  ],
  [
    'postmortem',
    'Incident Postmortem',
    'Learning after a service failure',
    'beginner',
    'A postmortem captures timeline, contributing factors, impact, detection, response, and follow-up work after an incident.',
    'focus the review on system learning and concrete follow-up ownership.',
    ['Retrospective', 'Timeline', 'Corrective Action', 'Blameless'],
  ],
  [
    'blameless-review',
    'Blameless Review',
    'Understanding decisions in context',
    'beginner',
    'A blameless review examines how systems and conditions shaped decisions instead of stopping at individual fault.',
    'ask what made the wrong action reasonable at the time.',
    ['Postmortem', 'Human Factors', 'Learning', 'Safety'],
  ],
  [
    'toil',
    'Toil',
    'Manual operational work that should shrink',
    'intermediate',
    'Toil is repetitive, manual, automatable operational work that scales with service load without creating lasting value.',
    'separate toil reduction from normal hard engineering work when planning reliability investment.',
    ['Automation', 'SRE', 'Runbook', 'Operational Load'],
  ],
  [
    'automation',
    'Reliability Automation',
    'Turning safe repeatable response into code',
    'intermediate',
    'Reliability automation removes repeated manual steps from diagnosis, remediation, and evidence collection.',
    'automate the stable step after the team understands its guardrails and failure modes.',
    ['Toil', 'Runbook', 'Approval', 'Rollback'],
  ],
  [
    'canary-analysis',
    'Canary Analysis',
    'Comparing new and baseline behavior',
    'intermediate',
    'Canary analysis compares telemetry from a new release slice with baseline behavior before rollout expands.',
    'name the rollback signals before traffic is shifted.',
    ['Progressive Delivery', 'Error Rate', 'Latency', 'Rollback'],
  ],
  [
    'rollback-signal',
    'Rollback Signal',
    'Telemetry that stops a bad release',
    'beginner',
    'A rollback signal is a metric, alert, or guardrail that indicates a release should be reverted or halted.',
    'define rollback signals while the team is calm, not during the release.',
    ['Canary', 'SLO', 'Deployment', 'Guardrail'],
  ],
  [
    'dependency-map',
    'Dependency Map',
    'A view of upstream and downstream risk',
    'intermediate',
    'A dependency map shows which services, stores, queues, and vendors interact with a service.',
    'use dependency mapping to ask whether the incident is local or a downstream symptom.',
    ['Service Map', 'Trace', 'Blast Radius', 'Ownership'],
  ],
  [
    'service-map',
    'Service Map',
    'Runtime relationships among services',
    'intermediate',
    'A service map uses telemetry and metadata to visualize service calls, dependencies, and health.',
    'compare the runtime service map with the architecture diagram when reality may have drifted.',
    ['Trace', 'Dependency', 'Topology', 'Metadata'],
  ],
  [
    'otel-collector',
    'OpenTelemetry Collector',
    'A pipeline for telemetry processing',
    'intermediate',
    'The OpenTelemetry Collector receives, processes, and exports telemetry between instrumented systems and backends.',
    'ask where filtering, enrichment, sampling, and routing occur before selecting a backend.',
    ['Receiver', 'Processor', 'Exporter', 'OpenTelemetry'],
  ],
  [
    'instrumentation',
    'Instrumentation',
    'Adding useful signals to code and systems',
    'beginner',
    'Instrumentation adds telemetry emission to applications, libraries, infrastructure, and workflows.',
    'include instrumentation in delivery scope when supportability matters.',
    ['SDK', 'OpenTelemetry', 'Span', 'Metric'],
  ],
  [
    'exemplar',
    'Metric Exemplar',
    'A metric point linked to trace context',
    'advanced',
    'An exemplar links aggregated metric data to representative trace context for deeper investigation.',
    'use exemplars when a spike should lead directly from a chart to a concrete request trace.',
    ['Histogram', 'Trace ID', 'Metric', 'Drill-Down'],
  ],
  [
    'log-retention',
    'Log Retention',
    'How long event records stay searchable',
    'beginner',
    'Log retention defines how long logs remain hot, archived, or deleted under cost, privacy, and investigation needs.',
    'ask whether retention covers incident investigation and audit needs without keeping sensitive data blindly.',
    ['Archive', 'Privacy', 'SIEM', 'Cost'],
  ],
  [
    'telemetry-pipeline',
    'Telemetry Pipeline',
    'How signals move to analysis tools',
    'intermediate',
    'A telemetry pipeline collects, transforms, routes, stores, and governs signals from producers to backends.',
    'draw the telemetry pipeline when teams disagree about loss, delay, cost, or ownership.',
    ['Collector', 'Sampling', 'Backend', 'Retention'],
  ],
  [
    'observability-cost',
    'Observability Cost',
    'The price of signal volume and retention',
    'intermediate',
    'Observability cost comes from ingest, storage, cardinality, retention, query, and vendor pricing choices.',
    'ask which signals are high value before treating every byte as equally worth retaining.',
    ['Sampling', 'Retention', 'Cardinality', 'FinOps'],
  ],
  [
    'noise-reduction',
    'Alert Noise Reduction',
    'Lowering interruptions that do not help',
    'intermediate',
    'Alert noise reduction removes duplicate, unactionable, low-signal, or badly routed notifications.',
    'review noisy alerts as reliability debt because ignored pages become missed incidents.',
    ['Alert Fatigue', 'Deduplication', 'Runbook', 'Paging'],
  ],
  [
    'freshness-sli',
    'Freshness SLI',
    'How recent required data or work is',
    'intermediate',
    'A freshness SLI measures whether data, jobs, caches, or replicas are updated within an expected delay.',
    'use freshness when success depends on timeliness rather than endpoint reachability.',
    ['Lag', 'Heartbeat', 'Pipeline', 'SLO'],
  ],
];

const identitySeeds: Seed[] = [
  [
    'authentication',
    'Authentication',
    'Proving who or what is present',
    'beginner',
    'Authentication verifies the identity of a user, device, workload, or service before trust decisions continue.',
    'name who is authenticating to whom before the meeting drifts into permissions.',
    ['Credential', 'MFA', 'Session', 'Identity Provider'],
  ],
  [
    'authorization',
    'Authorization',
    'Deciding what an identity may do',
    'beginner',
    'Authorization evaluates permissions and policy after an identity is known.',
    'separate sign-in success from whether the principal may perform the requested action.',
    ['RBAC', 'Policy', 'Least Privilege', 'Scope'],
  ],
  [
    'principal',
    'Principal',
    'An identity that can act',
    'beginner',
    'A principal is a user, group, service, workload, or device identity that can authenticate and receive permissions.',
    'ask which principal owns the action when auditability matters.',
    ['Subject', 'Service Account', 'Role', 'Audit Log'],
  ],
  [
    'credential',
    'Credential',
    'Evidence used to authenticate',
    'beginner',
    'A credential is evidence such as a password, key, certificate, passkey, or token used in an authentication flow.',
    'ask how the credential is issued, stored, rotated, and revoked.',
    ['Secret', 'Certificate', 'Token', 'Passkey'],
  ],
  [
    'factor',
    'Authentication Factor',
    'A category of sign-in evidence',
    'beginner',
    'An authentication factor is something you know, have, or are, used to prove identity.',
    'check whether the factors resist the actual attack path under discussion.',
    ['MFA', 'Password', 'Security Key', 'Biometric'],
  ],
  [
    'mfa',
    'Multi-Factor Authentication',
    'More than one factor for sign-in',
    'beginner',
    'MFA requires evidence from more than one authentication factor to reduce account takeover risk.',
    'ask whether MFA is enrolled, enforced, and strong for privileged identities.',
    ['Factor', 'Phishing Resistance', 'Conditional Access', 'Account Takeover'],
  ],
  [
    'phishing-resistant-mfa',
    'Phishing-Resistant MFA',
    'Authentication that resists credential relay',
    'intermediate',
    'Phishing-resistant MFA uses cryptographic binding and origin checks, as with passkeys or security keys, to resist fake login pages.',
    'prefer phishing-resistant factors for admins and high-risk access paths.',
    ['FIDO2', 'WebAuthn', 'Passkey', 'Security Key'],
  ],
  [
    'passwordless',
    'Passwordless Authentication',
    'Sign-in without a reusable password',
    'beginner',
    'Passwordless authentication uses device-bound keys, passkeys, certificates, or other flows instead of reusable passwords.',
    'ask what recovery path replaces the password before claiming the flow is stronger end to end.',
    ['Passkey', 'Recovery', 'MFA', 'Credential'],
  ],
  [
    'passkey',
    'Passkey',
    'A phishing-resistant credential for users',
    'beginner',
    'A passkey is a public-key credential bound to an account and unlocked on a device with local user verification.',
    'explain whether passkeys sync, where recovery happens, and which devices are supported.',
    ['WebAuthn', 'FIDO2', 'Passwordless', 'Public Key'],
  ],
  [
    'sso',
    'Single Sign-On',
    'One identity flow for many apps',
    'beginner',
    'Single sign-on lets users authenticate through a central identity provider and access multiple applications under managed policy.',
    'ask which apps still bypass SSO because exceptions become access blind spots.',
    ['Identity Provider', 'Federation', 'SAML', 'OIDC'],
  ],
  [
    'federation',
    'Identity Federation',
    'Trust between identity systems',
    'intermediate',
    'Identity federation lets one system rely on identity assertions or tokens issued by another trusted identity provider.',
    'state the trust relationship and token boundary before discussing user experience.',
    ['SAML', 'OIDC', 'Trust', 'Service Provider'],
  ],
  [
    'identity-provider',
    'Identity Provider',
    'The system that authenticates identities',
    'beginner',
    'An identity provider authenticates users or workloads and issues assertions, sessions, or tokens consumed by applications.',
    'ask whether policy is enforced at the IdP, the app, or both.',
    ['SSO', 'Federation', 'Token', 'Directory'],
  ],
  [
    'service-provider',
    'Service Provider',
    'The relying application in federation',
    'intermediate',
    'A service provider relies on an identity provider to authenticate users before granting application access.',
    'confirm what the application validates after it receives the assertion or token.',
    ['SAML', 'Relying Party', 'Assertion', 'SSO'],
  ],
  [
    'oauth',
    'OAuth 2.0',
    'Delegated authorization for APIs',
    'intermediate',
    'OAuth 2.0 lets a client receive limited access to protected resources without handling the resource owner password.',
    'call OAuth an authorization framework and use OIDC when identity is the question.',
    ['Access Token', 'Scope', 'Authorization Server', 'OIDC'],
  ],
  [
    'oidc',
    'OpenID Connect',
    'Identity on top of OAuth',
    'intermediate',
    'OpenID Connect adds authentication and identity claims to OAuth-based flows.',
    'ask whether the app needs an ID token for sign-in or an access token for an API.',
    ['OAuth', 'ID Token', 'Claims', 'Relying Party'],
  ],
  [
    'saml',
    'SAML',
    'XML-based enterprise federation',
    'intermediate',
    'SAML exchanges signed assertions between identity providers and service providers, often for enterprise browser SSO.',
    'mention SAML when enterprise federation and existing SaaS integrations are the practical constraint.',
    ['Assertion', 'SSO', 'Identity Provider', 'Metadata'],
  ],
  [
    'access-token',
    'Access Token',
    'Proof a client may call a resource',
    'beginner',
    'An access token represents delegated authorization used by APIs to accept a client request.',
    'ask for audience, scope, lifetime, and revocation behavior before trusting a token plan.',
    ['OAuth', 'Scope', 'Audience', 'Bearer Token'],
  ],
  [
    'id-token',
    'ID Token',
    'Identity claims for sign-in',
    'intermediate',
    'An ID token carries identity information for the client in an OpenID Connect authentication flow.',
    'do not send ID tokens to APIs as a substitute for access tokens.',
    ['OIDC', 'Claims', 'Access Token', 'Subject'],
  ],
  [
    'refresh-token',
    'Refresh Token',
    'A way to obtain new access tokens',
    'intermediate',
    'A refresh token lets a client request a new access token without forcing the user through full authentication again.',
    'ask how refresh tokens are stored and rotated because they extend session power.',
    ['OAuth', 'Rotation', 'Session', 'Access Token'],
  ],
  [
    'jwt',
    'JWT',
    'A signed token format',
    'intermediate',
    'A JSON Web Token is a compact token format with claims that may be signed and validated by consumers.',
    'ask which claims are trusted and how signature, issuer, audience, and expiry are validated.',
    ['JWS', 'Claims', 'OIDC', 'Bearer Token'],
  ],
  [
    'scope',
    'OAuth Scope',
    'A requested slice of delegated access',
    'intermediate',
    'A scope labels requested access in an OAuth flow, such as reading profile data or writing calendar events.',
    'avoid using broad scopes when the integration needs one narrow capability.',
    ['Consent', 'Access Token', 'Least Privilege', 'OAuth'],
  ],
  [
    'audience',
    'Token Audience',
    'The intended receiver of a token',
    'intermediate',
    'The audience claim identifies the service or client a token is intended for.',
    'validate audience so a token minted for one API is not accepted by another.',
    ['JWT', 'Issuer', 'Claim', 'Access Token'],
  ],
  [
    'claims',
    'Identity Claims',
    'Attributes carried about a subject',
    'beginner',
    'Claims are statements about an identity or token context, such as subject, email, group, issuer, or authentication time.',
    'ask which claim is authoritative before building policy on it.',
    ['JWT', 'Attribute', 'OIDC', 'Policy'],
  ],
  [
    'session',
    'Session',
    'State after a successful sign-in',
    'beginner',
    'A session maintains authenticated state between requests through cookies, tokens, server state, or combinations of them.',
    'ask how sessions expire, refresh, revoke, and survive privilege changes.',
    ['Cookie', 'Token', 'Logout', 'Session Fixation'],
  ],
  [
    'rbac',
    'Role-Based Access Control',
    'Permissions grouped by role',
    'beginner',
    'RBAC assigns permissions through roles such as support agent, billing admin, or read-only auditor.',
    'use RBAC when job-function roles are stable enough to manage permissions cleanly.',
    ['Role', 'Permission', 'Least Privilege', 'Access Review'],
  ],
  [
    'abac',
    'Attribute-Based Access Control',
    'Policy based on attributes and context',
    'intermediate',
    'ABAC evaluates attributes such as department, sensitivity, device posture, region, or resource owner in policy decisions.',
    'choose ABAC when context matters more than a static role list.',
    ['Policy Engine', 'Claim', 'Conditional Access', 'Resource Attribute'],
  ],
  [
    'rebac',
    'Relationship-Based Access Control',
    'Permissions from relationships',
    'advanced',
    'ReBAC grants access based on relationships such as document owner, project member, manager, or organization tenant.',
    'use relationship language when sharing and hierarchy drive permission decisions.',
    ['Authorization Graph', 'Owner', 'Tenant', 'Policy'],
  ],
  [
    'least-privilege',
    'Least Privilege',
    'Only the access needed for the job',
    'beginner',
    'Least privilege limits identities to the permissions and duration needed to complete required work.',
    'ask which permission can be removed without blocking the workflow.',
    ['RBAC', 'JIT Access', 'Access Review', 'Privilege Creep'],
  ],
  [
    'privilege-creep',
    'Privilege Creep',
    'Access accumulated over time',
    'beginner',
    'Privilege creep happens when users and services keep old permissions after role, project, or system changes.',
    'treat accumulated access as expected drift that needs review and automation.',
    ['Access Review', 'Least Privilege', 'JML', 'Audit'],
  ],
  [
    'access-review',
    'Access Review',
    'Confirming existing access is still needed',
    'beginner',
    'An access review asks accountable owners to confirm that permissions remain appropriate.',
    'ask who can make an informed review decision rather than sending a checkbox to everyone.',
    ['Certification', 'Manager Review', 'Least Privilege', 'Audit'],
  ],
  [
    'pam',
    'Privileged Access Management',
    'Controls for powerful identities',
    'intermediate',
    'Privileged Access Management protects admin access with vaulting, approvals, session controls, monitoring, and just-in-time elevation.',
    'name the privileged path separately from ordinary employee access.',
    ['JIT Access', 'Vault', 'Session Recording', 'Break Glass'],
  ],
  [
    'jit-access',
    'Just-in-Time Access',
    'Temporary elevation when needed',
    'intermediate',
    'Just-in-time access grants elevated permission for a short approved window and removes it automatically.',
    'prefer time-bound admin rights over standing privilege when operations allow it.',
    ['PAM', 'Approval', 'Least Privilege', 'Elevation'],
  ],
  [
    'break-glass',
    'Break Glass Access',
    'Emergency access under special control',
    'intermediate',
    'Break glass access is an emergency path for critical recovery when normal controls or systems are unavailable.',
    'ask how break glass access is protected, logged, tested, and reviewed after use.',
    ['Emergency Account', 'PAM', 'Audit', 'Recovery'],
  ],
  [
    'service-account',
    'Service Account',
    'A non-human identity for software',
    'beginner',
    'A service account represents software or automation that needs identity and permissions.',
    'ask whether the non-human identity has an owner and narrower rights than a human admin.',
    ['Workload Identity', 'API Key', 'IAM Role', 'Rotation'],
  ],
  [
    'workload-identity',
    'Workload Identity',
    'Identity tied to running software',
    'intermediate',
    'Workload identity lets running code authenticate using platform-issued identity instead of embedded long-lived secrets.',
    'prefer workload identity when cloud or cluster context can issue short-lived credentials.',
    ['Service Account', 'Federation', 'IAM Role', 'Secretless'],
  ],
  [
    'secretless-auth',
    'Secretless Authentication',
    'Reducing embedded credentials',
    'intermediate',
    'Secretless authentication removes stored application secrets where platform identity or short-lived exchange can replace them.',
    'ask whether a secret is truly required before planning rotation and storage.',
    ['Managed Identity', 'Workload Identity', 'Certificate', 'Token'],
  ],
  [
    'scim',
    'SCIM',
    'Automated identity provisioning for SaaS',
    'intermediate',
    'SCIM standardizes provisioning and deprovisioning users and groups between identity systems and applications.',
    'ask whether deprovisioning is automated before trusting SSO alone for lifecycle control.',
    ['Provisioning', 'Group Sync', 'JML', 'SaaS'],
  ],
  [
    'jml',
    'Joiner-Mover-Leaver',
    'Lifecycle events for workforce identity',
    'beginner',
    'Joiner-mover-leaver processes grant, change, and remove access when people join, change roles, or leave.',
    'map access lifecycle to HR and manager events before adding another manual request form.',
    ['SCIM', 'Access Review', 'Deprovisioning', 'HRIS'],
  ],
  [
    'device-trust',
    'Device Trust',
    'Confidence in the endpoint',
    'intermediate',
    'Device trust evaluates whether an endpoint meets policy, such as management state, encryption, patch level, and risk posture.',
    'include device posture when user identity alone is not enough for the access risk.',
    ['Conditional Access', 'MDM', 'Endpoint', 'Zero Trust'],
  ],
  [
    'conditional-access',
    'Conditional Access',
    'Access decisions with context',
    'intermediate',
    'Conditional access applies policy based on identity, device, location, session risk, sensitivity, and authentication strength.',
    'state the condition and fallback experience before imposing a new access rule.',
    ['MFA', 'Device Trust', 'ABAC', 'Risk-Based Auth'],
  ],
  [
    'risk-based-auth',
    'Risk-Based Authentication',
    'Changing challenge strength by risk',
    'intermediate',
    'Risk-based authentication increases verification when signals suggest unusual or risky sign-in behavior.',
    'ask what risk signal triggers friction and how false positives are handled.',
    ['Conditional Access', 'MFA', 'Impossible Travel', 'Anomaly'],
  ],
  [
    'pki-identity',
    'PKI Identity',
    'Identity backed by certificates',
    'advanced',
    'Public Key Infrastructure binds keys to identities through certificates, trust chains, issuance, and revocation processes.',
    'ask who issues, rotates, and revokes certificates before treating them as an identity foundation.',
    ['Certificate Authority', 'mTLS', 'CRL', 'OCSP'],
  ],
  [
    'certificate-auth',
    'Certificate Authentication',
    'Proving identity with key possession',
    'intermediate',
    'Certificate authentication verifies that a client or service controls the private key associated with a trusted certificate.',
    'distinguish certificate identity from the policy that authorizes what it may do.',
    ['PKI', 'mTLS', 'Private Key', 'Trust Store'],
  ],
  [
    'mtls-identity',
    'mTLS Service Identity',
    'Mutual certificate proof between services',
    'intermediate',
    'mTLS lets services authenticate each other with certificates while encrypting traffic in transit.',
    'ask whether service identity and authorization are both defined, not only encryption.',
    ['Certificate', 'Service Mesh', 'Authorization', 'Zero Trust'],
  ],
  [
    'directory-group',
    'Directory Group',
    'A managed collection of identities',
    'beginner',
    'Directory groups organize users or services for access assignment, communication, and policy targeting.',
    'ask whether a group is role-based, dynamic, and owned before using it for critical access.',
    ['Directory', 'RBAC', 'Group Sync', 'Owner'],
  ],
  [
    'tenant',
    'Identity Tenant',
    'An administrative trust boundary',
    'beginner',
    'An identity tenant is a scoped administrative environment for identities, policies, apps, and trust configuration.',
    'name the tenant boundary when discussing cross-company or cross-environment trust.',
    ['Directory', 'Domain', 'Federation', 'Isolation'],
  ],
  [
    'identity-lifecycle',
    'Identity Lifecycle',
    'Creation through retirement of identity',
    'beginner',
    'Identity lifecycle covers enrollment, provisioning, changes, reviews, credential rotation, suspension, and deletion.',
    'ask what event retires stale human and non-human identities.',
    ['JML', 'SCIM', 'Access Review', 'Deprovisioning'],
  ],
  [
    'identity-audit-log',
    'Identity Audit Log',
    'Evidence of access and policy activity',
    'beginner',
    'Identity audit logs record sign-ins, token events, admin actions, policy decisions, and lifecycle changes.',
    'ask which log proves the access path when compliance or investigation matters.',
    ['SIEM', 'Sign-In Log', 'Admin Event', 'Retention'],
  ],
  [
    'non-human-identity',
    'Non-Human Identity',
    'Identity for automation and machines',
    'intermediate',
    'Non-human identities include service accounts, bots, workloads, devices, integrations, and automation actors.',
    'count non-human identities in the threat model because they often outnumber people.',
    ['Service Account', 'Workload Identity', 'API Key', 'Owner'],
  ],
  [
    'token-revocation',
    'Token Revocation',
    'Invalidating access before expiry',
    'intermediate',
    'Token revocation stops a token or session from being accepted before its normal expiration.',
    'ask what happens after compromise when a token cannot simply be recalled instantly everywhere.',
    ['Expiry', 'Refresh Token', 'Session', 'Introspection'],
  ],
];

const architectureSeeds: Seed[] = [
  [
    'requirements',
    'Architecture Requirements',
    'Constraints a design must satisfy',
    'beginner',
    'Architecture requirements include functional needs plus quality attributes, constraints, compliance, scale, and operational expectations.',
    'separate must-have constraints from preferences before comparing design options.',
    ['Quality Attribute', 'Constraint', 'Use Case', 'Trade-Off'],
  ],
  [
    'quality-attributes',
    'Quality Attributes',
    'Non-functional design goals',
    'beginner',
    'Quality attributes describe how a system should behave, including reliability, latency, security, scalability, and maintainability.',
    'name the quality attribute being optimized when a design choice costs complexity.',
    ['Availability', 'Performance', 'Security', 'Maintainability'],
  ],
  [
    'trade-off',
    'Architecture Trade-Off',
    'What improves and what it costs',
    'beginner',
    'An architecture trade-off states which property improves, which property worsens, and why that balance fits the constraints.',
    'ask what the design buys and what it makes harder.',
    ['Constraint', 'ADR', 'Quality Attribute', 'Decision'],
  ],
  [
    'c4-diagram',
    'C4 Diagram',
    'System views at different zoom levels',
    'beginner',
    'C4 diagrams describe context, containers, components, and code so architecture discussions use the right level of detail.',
    'choose the diagram level that answers the meeting question instead of showing every class.',
    ['Context Diagram', 'Container', 'Component', 'Boundary'],
  ],
  [
    'adr',
    'Architecture Decision Record',
    'A concise record of a design decision',
    'beginner',
    'An ADR captures context, decision, alternatives, and consequences for an architecture choice.',
    'write the decision and consequences while the rationale is still fresh.',
    ['Trade-Off', 'Decision Log', 'Constraint', 'Review'],
  ],
  [
    'bounded-context',
    'Bounded Context',
    'A boundary where a model has meaning',
    'intermediate',
    'A bounded context defines where domain language, rules, and data meaning stay consistent.',
    'ask whether the teams share one model or need an explicit boundary and translation.',
    ['DDD', 'Context Map', 'Domain Event', 'Service Boundary'],
  ],
  [
    'modular-monolith',
    'Modular Monolith',
    'One deployment with strong internal boundaries',
    'intermediate',
    'A modular monolith keeps modules separated inside one deployable system rather than splitting too early into services.',
    'consider a modular monolith when independent deployment is not yet worth distributed complexity.',
    ['Module', 'Microservice', 'Boundary', 'Refactor'],
  ],
  [
    'microservices',
    'Microservices',
    'Independently deployable service boundaries',
    'intermediate',
    'Microservices split capabilities into independently deployable services with separate ownership and communication contracts.',
    'ask which team autonomy or scaling need justifies the operational cost of service separation.',
    ['Service Boundary', 'API', 'Data Ownership', 'Observability'],
  ],
  [
    'event-driven',
    'Event-Driven Architecture',
    'Reacting to facts that happened',
    'intermediate',
    'Event-driven architecture lets producers publish events and consumers react asynchronously without direct request coupling.',
    'ask what becomes eventually consistent when the flow moves to events.',
    ['Event', 'Queue', 'Pub/Sub', 'Idempotency'],
  ],
  [
    'sync-vs-async',
    'Synchronous vs Asynchronous',
    'Waiting now or processing later',
    'beginner',
    'Synchronous calls wait for a response in the caller path, while asynchronous flows decouple work through messages or jobs.',
    'keep user wait time and failure coupling visible when choosing sync or async.',
    ['Queue', 'Timeout', 'Workflow', 'Latency'],
  ],
  [
    'api-gateway',
    'API Gateway',
    'An edge entry point for APIs',
    'beginner',
    'An API gateway routes external API traffic and can centralize concerns such as auth, rate limits, and request policy.',
    'ask which concern belongs at the edge and which still belongs in the service.',
    ['Reverse Proxy', 'Rate Limit', 'Authentication', 'North-South Traffic'],
  ],
  [
    'service-mesh',
    'Service Mesh',
    'Infrastructure for service-to-service traffic',
    'advanced',
    'A service mesh manages service communication concerns such as mTLS, retries, policy, and telemetry around workloads.',
    'justify mesh complexity with cross-service traffic needs the platform cannot handle more simply.',
    ['Sidecar', 'mTLS', 'Telemetry', 'East-West Traffic'],
  ],
  [
    'caching',
    'Caching',
    'Serving reused data faster',
    'beginner',
    'Caching stores reusable results closer to demand to reduce latency, load, or cost.',
    'ask what is cached, how stale it may be, and what invalidates it.',
    ['TTL', 'Cache Aside', 'Latency', 'Invalidation'],
  ],
  [
    'cache-invalidation',
    'Cache Invalidation',
    'Removing stale cached results',
    'intermediate',
    'Cache invalidation defines when stale entries are expired, replaced, or bypassed after source data changes.',
    'make stale-data behavior explicit before celebrating cache hit rate.',
    ['TTL', 'Event', 'Write Through', 'Consistency'],
  ],
  [
    'load-balancer',
    'Load Balancer',
    'Traffic distribution across backends',
    'beginner',
    'A load balancer routes traffic to healthy backend targets according to protocol and balancing policy.',
    'ask what health check proves a target can serve real work.',
    ['Health Check', 'Target', 'TLS', 'Horizontal Scaling'],
  ],
  [
    'horizontal-scaling',
    'Horizontal Scaling',
    'Adding more instances',
    'beginner',
    'Horizontal scaling adds instances or workers to handle more demand.',
    'ask whether state and bottlenecks allow replicas to help.',
    ['Stateless', 'Load Balancer', 'Partition', 'Autoscaling'],
  ],
  [
    'vertical-scaling',
    'Vertical Scaling',
    'Making one node larger',
    'beginner',
    'Vertical scaling increases resources on one node, such as CPU, memory, or storage throughput.',
    'call out the ceiling and failover risk when the plan relies on bigger nodes.',
    ['CPU', 'Memory', 'Single Node', 'Bottleneck'],
  ],
  [
    'stateless',
    'Stateless Service',
    'Request handling without local session dependence',
    'beginner',
    'A stateless service can handle requests on any suitable instance because durable state is externalized.',
    'prefer stateless request paths when deployment and scaling need simple replacement.',
    ['Session Store', 'Horizontal Scaling', 'Replica', 'Cache'],
  ],
  [
    'stateful',
    'Stateful Component',
    'A component that owns durable state',
    'beginner',
    'A stateful component stores data or coordination state that affects recovery, scaling, and consistency.',
    'name state ownership before promising instance replacement is trivial.',
    ['Database', 'Replication', 'Backup', 'Leader'],
  ],
  [
    'partitioning',
    'Partitioning',
    'Splitting data or work into groups',
    'intermediate',
    'Partitioning divides data or workload by a key, range, time, tenant, or other rule.',
    'ask which partition key balances load and preserves the queries the system needs.',
    ['Shard', 'Hotspot', 'Range', 'Tenant'],
  ],
  [
    'sharding',
    'Sharding',
    'Distributing data across stores',
    'intermediate',
    'Sharding stores subsets of data on different nodes so one database limit does not cap total scale.',
    'surface rebalancing, cross-shard queries, and hotspot risk before approving sharding.',
    ['Partition Key', 'Database', 'Hotspot', 'Replication'],
  ],
  [
    'replication',
    'Replication',
    'Copies for availability or reads',
    'beginner',
    'Replication copies data or state to other nodes for durability, failover, locality, or read capacity.',
    'ask what lag and failover behavior consumers can tolerate.',
    ['Replica Lag', 'Failover', 'Leader', 'Consistency'],
  ],
  [
    'consistency',
    'Consistency Model',
    'Rules for what readers observe',
    'intermediate',
    'A consistency model defines what data values readers may observe after writes across distributed components.',
    'describe user-visible behavior instead of arguing strong and eventual consistency as slogans.',
    ['Eventual Consistency', 'Read After Write', 'Replication', 'CAP'],
  ],
  [
    'availability',
    'Availability Design',
    'Keeping service usable through failure',
    'beginner',
    'Availability design considers redundancy, failover, degradation, dependencies, and recovery paths.',
    'ask which failures the design survives and which still cause outage.',
    ['SLA', 'Failover', 'Fault Domain', 'Redundancy'],
  ],
  [
    'cap',
    'CAP Trade-Off',
    'Partition behavior in distributed systems',
    'advanced',
    'CAP highlights that during a network partition a distributed system must choose between accepting some inconsistency or rejecting some availability.',
    'use CAP to discuss partition behavior, not to label every database with a permanent two-letter identity.',
    ['Partition', 'Consistency', 'Availability', 'Distributed System'],
  ],
  [
    'eventual-consistency',
    'Eventual Consistency',
    'Convergence after a delay',
    'intermediate',
    'Eventual consistency allows replicas or downstream views to converge after propagation delay rather than immediately.',
    'ask what users see during the convergence window.',
    ['Replication Lag', 'Event', 'Read Model', 'Compensation'],
  ],
  [
    'queue',
    'Queue',
    'A buffer for asynchronous work',
    'beginner',
    'A queue decouples producers and consumers by storing work until consumers can process it.',
    'ask what happens when queue depth grows faster than workers can drain it.',
    ['Backpressure', 'DLQ', 'Worker', 'Retry'],
  ],
  [
    'backpressure',
    'Backpressure',
    'Slowing demand to protect capacity',
    'intermediate',
    'Backpressure limits intake or slows producers when downstream capacity cannot keep up.',
    'add backpressure before overload turns into retries and cascading failure.',
    ['Queue', 'Rate Limit', 'Saturation', 'Load Shedding'],
  ],
  [
    'idempotency',
    'Idempotency',
    'Safe repeats of an operation',
    'intermediate',
    'Idempotency ensures repeating an operation does not create extra business side effects.',
    'ask how retries avoid duplicate orders, charges, and events.',
    ['Retry', 'Idempotency Key', 'Deduplication', 'At Least Once'],
  ],
  [
    'circuit-breaker',
    'Circuit Breaker',
    'Fast failure around unhealthy dependencies',
    'intermediate',
    'A circuit breaker stops repeated calls to a failing dependency for a period so callers preserve capacity.',
    'use circuit breakers with timeouts and fallback behavior, not as a substitute for them.',
    ['Timeout', 'Fallback', 'Bulkhead', 'Dependency'],
  ],
  [
    'bulkhead',
    'Bulkhead Isolation',
    'Keeping failure pools separate',
    'advanced',
    'Bulkhead isolation separates resources so one failing path does not consume all capacity for others.',
    'ask which thread pool, queue, connection, or tenant boundary limits blast radius.',
    ['Circuit Breaker', 'Resource Pool', 'Blast Radius', 'Isolation'],
  ],
  [
    'timeout-budget',
    'Timeout Budget',
    'Allocating wait time across calls',
    'intermediate',
    'A timeout budget splits allowable user wait time across service hops and retries.',
    'set downstream timeouts lower than the caller deadline so failure returns in time to act.',
    ['Deadline', 'Retry', 'Latency', 'Dependency'],
  ],
  [
    'retry-policy',
    'Retry Policy',
    'Rules for trying failed work again',
    'intermediate',
    'A retry policy defines which failures are retried, how often, with what backoff, and under what idempotency guarantees.',
    'treat retries as extra load and design them deliberately.',
    ['Backoff', 'Jitter', 'Timeout', 'Idempotency'],
  ],
  [
    'rate-limiting',
    'Rate Limiting',
    'A cap on demand',
    'beginner',
    'Rate limiting controls request volume per client, tenant, route, or resource to protect capacity and fairness.',
    'ask whether the limit protects the service, a tenant, or an upstream dependency.',
    ['Quota', 'Throttle', '429', 'Abuse'],
  ],
  [
    'data-ownership',
    'Data Ownership',
    'Who writes and governs state',
    'intermediate',
    'Data ownership assigns authority for a dataset or state model to a boundary and its accountable team.',
    'avoid shared-write databases when ownership is the real unresolved design question.',
    ['Bounded Context', 'Schema', 'Service', 'Contract'],
  ],
  [
    'schema-evolution',
    'Schema Evolution',
    'Changing data formats safely',
    'intermediate',
    'Schema evolution changes stored or exchanged data formats while preserving required compatibility and migration behavior.',
    'ask how old consumers and old data behave during the change.',
    ['Migration', 'Backward Compatibility', 'Event Schema', 'Versioning'],
  ],
  [
    'versioning',
    'Interface Versioning',
    'Evolving contracts over time',
    'beginner',
    'Interface versioning manages incompatible API, message, or data contract changes while consumers migrate.',
    'use compatibility first and explicit versions when consumers need a migration window.',
    ['API', 'Deprecation', 'Schema', 'Contract'],
  ],
  [
    'dependency-direction',
    'Dependency Direction',
    'Which code or service relies on which',
    'intermediate',
    'Dependency direction shapes change impact by deciding which modules know about details and which expose stable contracts.',
    'ask whether high-level policy depends on volatile infrastructure detail.',
    ['Interface', 'Hexagonal', 'Module', 'Coupling'],
  ],
  [
    'hexagonal-boundary',
    'Hexagonal Boundary',
    'Ports around core behavior',
    'advanced',
    'Hexagonal architecture keeps core domain behavior behind ports while adapters handle databases, HTTP, queues, and vendors.',
    'use ports when changing infrastructure should not rewrite business decisions.',
    ['Adapter', 'Port', 'Domain', 'Testing'],
  ],
  [
    'strangler-migration',
    'Strangler Migration',
    'Replacing a legacy system incrementally',
    'intermediate',
    'A strangler migration routes slices of behavior away from a legacy system until the old path can be retired.',
    'ask which slice has clear ownership and rollback before planning a large rewrite.',
    ['Legacy', 'Routing', 'Incremental Delivery', 'Rollback'],
  ],
  [
    'single-point-of-failure',
    'Single Point of Failure',
    'One component that can stop the system',
    'beginner',
    'A single point of failure is a component whose loss causes required service behavior to fail.',
    'name the single points of failure and whether the business accepts them.',
    ['Redundancy', 'Failover', 'Dependency', 'Availability'],
  ],
  [
    'fault-domain',
    'Fault Domain',
    'A shared failure boundary',
    'intermediate',
    'A fault domain groups components that can fail together, such as a rack, zone, region, account, or vendor.',
    'spread redundancy across real fault domains instead of counting replicas in one place.',
    ['Availability Zone', 'Region', 'Blast Radius', 'Redundancy'],
  ],
  [
    'multi-region',
    'Multi-Region Design',
    'Using more than one geographic region',
    'advanced',
    'Multi-region design uses separate regions for latency, compliance, availability, or disaster recovery goals.',
    'ask whether the recovery target justifies data, traffic, and operations complexity across regions.',
    ['Failover', 'Replication', 'RTO', 'Data Residency'],
  ],
  [
    'dr-tier',
    'Disaster Recovery Tier',
    'The recovery posture chosen for a workload',
    'intermediate',
    'A disaster recovery tier sets how much standby capacity, replication, automation, and cost support recovery goals.',
    'match recovery posture to impact rather than giving every service the most expensive tier.',
    ['Backup', 'Warm Standby', 'RTO', 'RPO'],
  ],
  [
    'rto-rpo',
    'RTO and RPO',
    'Recovery time and data loss targets',
    'beginner',
    'RTO is how quickly service must recover; RPO is how much data loss in time is acceptable.',
    'ask for RTO and RPO before debating backup and failover architecture.',
    ['Disaster Recovery', 'Backup', 'Restore', 'Failover'],
  ],
  [
    'capacity-estimate',
    'Capacity Estimate',
    'Sizing demand against limits',
    'beginner',
    'A capacity estimate converts users, requests, payloads, growth, and peaks into rough resource demand.',
    'make assumptions explicit so the room can challenge the number instead of the person.',
    ['Throughput', 'Peak', 'Headroom', 'Quota'],
  ],
  [
    'hotspot',
    'Hotspot',
    'Uneven demand on one key or resource',
    'intermediate',
    'A hotspot occurs when a small subset of keys, tenants, routes, or nodes receives disproportionate load.',
    'ask whether the partition or cache plan survives skewed demand.',
    ['Partition', 'Shard', 'Skew', 'Rate Limit'],
  ],
  [
    'observability-design',
    'Observability by Design',
    'Supportability built into architecture',
    'beginner',
    'Observability by design adds signals, identifiers, dashboards, and failure evidence as part of system design.',
    'treat supportability as a design requirement instead of a post-launch patch.',
    ['Telemetry', 'Correlation ID', 'SLO', 'Runbook'],
  ],
  [
    'security-boundary',
    'Security Boundary',
    'Where trust changes',
    'intermediate',
    'A security boundary marks a change in trust, privilege, tenancy, or exposure that needs explicit controls.',
    'draw trust boundaries on the architecture before arguing controls.',
    ['Threat Model', 'Tenant', 'AuthZ', 'Network'],
  ],
  [
    'architecture-review',
    'Architecture Review',
    'A structured trade-off conversation',
    'beginner',
    'An architecture review tests a design against requirements, constraints, risks, alternatives, and operations.',
    'bring decisions, alternatives, risks, and open questions so the review can converge.',
    ['ADR', 'Risk', 'Constraint', 'Design Doc'],
  ],
];

const appsecSeeds: Seed[] = [
  [
    'threat-modeling',
    'Threat Modeling',
    'Finding design risk before code ships',
    'beginner',
    'Threat modeling identifies assets, actors, trust boundaries, abuse paths, and mitigations in a system design.',
    'start with what needs protection, who can reach it, and what changes at each trust boundary.',
    ['Asset', 'Trust Boundary', 'STRIDE', 'Mitigation'],
  ],
  [
    'asset',
    'Security Asset',
    'Something worth protecting',
    'beginner',
    'A security asset is data, capability, identity, money flow, availability, or trust relationship that attackers may target.',
    'name the asset before deciding whether a control is worth its cost.',
    ['Threat Model', 'Data Classification', 'Impact', 'Risk'],
  ],
  [
    'trust-boundary',
    'Trust Boundary',
    'Where privilege or exposure changes',
    'beginner',
    'A trust boundary separates components, actors, tenants, or networks that should not automatically trust each other.',
    'draw the trust boundary before assuming input is safe.',
    ['Threat Model', 'Validation', 'Tenant', 'Authorization'],
  ],
  [
    'stride',
    'STRIDE',
    'Threat categories for design review',
    'intermediate',
    'STRIDE prompts discussion of spoofing, tampering, repudiation, information disclosure, denial of service, and elevation of privilege.',
    'use STRIDE to widen the threat conversation without turning the meeting into a checklist only.',
    ['Threat Model', 'Spoofing', 'Tampering', 'Elevation of Privilege'],
  ],
  [
    'abuse-case',
    'Abuse Case',
    'How a feature can be misused',
    'beginner',
    'An abuse case describes a harmful path an attacker or bad actor may take through a feature.',
    'ask how the feature could be misused before testing only happy paths.',
    ['Misuse', 'Threat Model', 'Fraud', 'Control'],
  ],
  [
    'owasp-top-ten',
    'OWASP Top 10',
    'A common web application risk reference',
    'beginner',
    'The OWASP Top 10 summarizes common classes of web application security risk for awareness and prioritization.',
    'use OWASP language to orient risk, then map it to the actual application path.',
    ['Web Security', 'Injection', 'Access Control', 'Security Misconfiguration'],
  ],
  [
    'injection',
    'Injection',
    'Untrusted input interpreted as commands',
    'beginner',
    'Injection happens when untrusted input changes the meaning of a command, query, template, or interpreter operation.',
    'ask where untrusted input crosses into an interpreter.',
    ['SQL Injection', 'Command Injection', 'Parameterization', 'Validation'],
  ],
  [
    'xss',
    'Cross-Site Scripting',
    'Script execution in another user browser',
    'beginner',
    'XSS lets attacker-controlled content execute as script in a victim browser under the application origin.',
    'ask where output encoding and content policy prevent untrusted content from becoming code.',
    ['Output Encoding', 'CSP', 'Browser', 'DOM'],
  ],
  [
    'csrf',
    'Cross-Site Request Forgery',
    'Forcing a browser to send an unwanted request',
    'intermediate',
    'CSRF abuses ambient browser credentials so a victim browser submits a state-changing request the user did not intend.',
    'ask whether cookies, SameSite policy, and CSRF tokens protect state-changing routes.',
    ['SameSite', 'CSRF Token', 'Cookie', 'Session'],
  ],
  [
    'ssrf',
    'Server-Side Request Forgery',
    'Tricking servers into fetching unsafe targets',
    'intermediate',
    'SSRF occurs when attackers influence server-side outbound requests to reach internal, metadata, or unintended resources.',
    'ask what URLs the server may fetch and how network egress is constrained.',
    ['Allowlist', 'Metadata Service', 'Egress', 'URL Parser'],
  ],
  [
    'idor',
    'IDOR and BOLA',
    'Object access without proper authorization',
    'beginner',
    'IDOR or BOLA flaws let callers access objects by changing identifiers when object-level authorization is missing.',
    'ask whether every object lookup checks the caller relationship to that object.',
    ['Authorization', 'Tenant', 'Object ID', 'Access Control'],
  ],
  [
    'authz-flaw',
    'Authorization Flaw',
    'A permission check missing or wrong',
    'beginner',
    'An authorization flaw allows an identity to take an action or reach data outside intended policy.',
    'test authorization on the server path, not only in the UI.',
    ['RBAC', 'Policy', 'IDOR', 'Least Privilege'],
  ],
  [
    'deserialization',
    'Unsafe Deserialization',
    'Trusting hostile serialized data',
    'advanced',
    'Unsafe deserialization occurs when untrusted serialized data creates dangerous objects, state, or code paths.',
    'ask whether the format and parser can instantiate behavior rather than plain data.',
    ['Parser', 'Gadget', 'Input Trust', 'Serialization'],
  ],
  [
    'command-injection',
    'Command Injection',
    'Input reaching shell or process commands',
    'intermediate',
    'Command injection lets untrusted input alter operating system commands executed by an application.',
    'prefer safe APIs and argument separation over constructing shell strings.',
    ['Injection', 'Shell', 'Escaping', 'Least Privilege'],
  ],
  [
    'path-traversal',
    'Path Traversal',
    'Escaping intended file boundaries',
    'beginner',
    'Path traversal uses attacker-controlled paths to access files outside an intended directory.',
    'ask how canonical paths, allowlists, and storage isolation constrain file access.',
    ['File System', 'Validation', 'Upload', 'Sandbox'],
  ],
  [
    'file-upload',
    'File Upload Risk',
    'Hostile content entering storage and processing',
    'intermediate',
    'File uploads can carry malware, oversized payloads, active content, traversal names, and parser exploits.',
    'treat uploaded files as untrusted through storage, scanning, rendering, and download.',
    ['Content Type', 'Malware Scan', 'Size Limit', 'Object Storage'],
  ],
  [
    'secrets-in-code',
    'Secrets in Code',
    'Credentials committed with software',
    'beginner',
    'Secrets in code expose tokens, passwords, and keys through repositories, logs, packages, and build artifacts.',
    'ask how the secret is removed, rotated, and prevented from returning.',
    ['Secret Scanning', 'Vault', 'Rotation', 'Build Log'],
  ],
  [
    'dependency-vulnerability',
    'Dependency Vulnerability',
    'Risk inherited from third-party code',
    'beginner',
    'Dependency vulnerabilities are security flaws in libraries, packages, base images, or transitive components the application uses.',
    'ask whether the vulnerable path is reachable and what upgrade or mitigation fits release risk.',
    ['SCA', 'CVE', 'Transitive Dependency', 'SBOM'],
  ],
  [
    'sbom',
    'Software Bill of Materials',
    'Inventory of software components',
    'beginner',
    'An SBOM lists components and versions in software artifacts to support review, vulnerability response, and supply chain visibility.',
    'use the SBOM to answer what shipped before debating remediation scope.',
    ['Dependency', 'Artifact', 'Supply Chain', 'Provenance'],
  ],
  [
    'sast',
    'Static Application Security Testing',
    'Source and build-time code analysis',
    'beginner',
    'SAST analyzes code or build artifacts for security-relevant patterns without executing the application.',
    'ask which findings are actionable in this codebase before making SAST a blocking gate.',
    ['Scanner', 'False Positive', 'Code Review', 'CI'],
  ],
  [
    'dast',
    'Dynamic Application Security Testing',
    'Testing a running application',
    'beginner',
    'DAST probes a running application from the outside for security behavior and exposed flaws.',
    'use DAST to test deployed behavior, then pair it with code context for remediation.',
    ['Scanner', 'Runtime', 'Web Security', 'Pentest'],
  ],
  [
    'sca',
    'Software Composition Analysis',
    'Dependency and license security scanning',
    'beginner',
    'SCA analyzes third-party components for vulnerabilities, versions, licenses, and supply chain policy.',
    'ask whether the finding is direct, transitive, reachable, and fixable.',
    ['Dependency', 'SBOM', 'CVE', 'License'],
  ],
  [
    'iast',
    'Interactive Application Security Testing',
    'Runtime insight during test execution',
    'advanced',
    'IAST observes application behavior from inside the runtime while tests exercise code paths.',
    'consider IAST when the team needs runtime context tied to test coverage.',
    ['Runtime', 'DAST', 'Instrumentation', 'Test'],
  ],
  [
    'fuzzing',
    'Fuzzing',
    'Unexpected inputs at scale',
    'intermediate',
    'Fuzzing generates varied or malformed inputs to discover crashes, parser flaws, and unsafe assumptions.',
    'use fuzzing where parsers and state machines face hostile input.',
    ['Parser', 'Crash', 'Property Test', 'Input Validation'],
  ],
  [
    'secure-code-review',
    'Secure Code Review',
    'Reviewing change paths for security impact',
    'beginner',
    'Secure code review examines trust boundaries, authorization, input handling, secrets, crypto, and risky dependencies in a change.',
    'focus review on the changed attack surface and data flow.',
    ['Threat Model', 'Pull Request', 'AuthZ', 'Data Flow'],
  ],
  [
    'security-unit-test',
    'Security Test',
    'Executable proof for a protection',
    'beginner',
    'A security test verifies controls such as authorization denial, validation, safe redirects, or token expiry.',
    'turn a fixed vulnerability into a regression test where behavior is testable.',
    ['Regression', 'Authorization', 'Validation', 'CI'],
  ],
  [
    'input-validation',
    'Input Validation',
    'Checking data fits expectations',
    'beginner',
    'Input validation constrains type, shape, range, length, format, and business rules for untrusted data.',
    'validate for correctness while still using context-specific output and query safety controls.',
    ['Allowlist', 'Schema', 'Parser', 'Injection'],
  ],
  [
    'output-encoding',
    'Output Encoding',
    'Rendering data safely in context',
    'beginner',
    'Output encoding transforms untrusted data for the specific destination context such as HTML, attribute, URL, or JavaScript.',
    'match encoding to output context instead of relying on generic escaping.',
    ['XSS', 'Template', 'HTML', 'Context'],
  ],
  [
    'parameterized-query',
    'Parameterized Query',
    'Separating query structure from data',
    'beginner',
    'Parameterized queries send values separately from query structure so input cannot rewrite SQL meaning.',
    'prefer parameterization over string-built SQL whenever user-controlled values reach queries.',
    ['SQL Injection', 'Database Driver', 'ORM', 'Prepared Statement'],
  ],
  [
    'csp',
    'Content Security Policy',
    'Browser policy that limits content execution',
    'intermediate',
    'Content Security Policy restricts sources and behaviors for scripts, styles, frames, and other browser content.',
    'treat CSP as defense in depth after output safety, not as permission to keep XSS.',
    ['XSS', 'Browser', 'Nonce', 'Security Header'],
  ],
  [
    'cookie-flags',
    'Cookie Flags',
    'Browser cookie security attributes',
    'beginner',
    'Cookie flags such as HttpOnly, Secure, and SameSite reduce script theft and cross-site request abuse.',
    'ask how cookie attributes match session threat assumptions.',
    ['Session', 'CSRF', 'HttpOnly', 'SameSite'],
  ],
  [
    'session-fixation',
    'Session Fixation',
    'Reusing a session identifier after login',
    'intermediate',
    'Session fixation lets an attacker set or know a session identifier before a victim authenticates.',
    'rotate session identifiers when authentication state changes.',
    ['Session', 'Cookie', 'Login', 'Regeneration'],
  ],
  [
    'tls-config',
    'TLS Configuration',
    'Transport encryption and identity settings',
    'beginner',
    'TLS configuration controls certificates, trust chains, protocol versions, ciphers, and termination points.',
    'ask where TLS terminates and which hop still carries sensitive data.',
    ['Certificate', 'HTTPS', 'mTLS', 'Cipher'],
  ],
  [
    'security-headers',
    'Security Headers',
    'Browser-facing policy metadata',
    'beginner',
    'Security headers communicate browser protections such as frame restrictions, transport policy, and content policy.',
    'use headers to reduce browser attack surface while keeping server controls primary.',
    ['CSP', 'HSTS', 'Clickjacking', 'Browser'],
  ],
  [
    'abuse-rate-limit',
    'Abuse Rate Limit',
    'Constraining harmful automated behavior',
    'beginner',
    'Abuse-oriented rate limits protect login, reset, search, export, and payment paths from brute force and automation.',
    'distinguish capacity throttles from abuse controls tied to attacker behavior.',
    ['Brute Force', 'Bot', 'Quota', 'Fraud'],
  ],
  [
    'sensitive-logging',
    'Sensitive Data in Logs',
    'Exposure through diagnostics',
    'beginner',
    'Sensitive logging occurs when secrets, tokens, personal data, or regulated content enters logs and traces unnecessarily.',
    'ask what must be redacted before broadening diagnostic capture.',
    ['Redaction', 'Token', 'PII', 'Retention'],
  ],
  [
    'crypto-misuse',
    'Cryptography Misuse',
    'Using crypto incorrectly',
    'intermediate',
    'Cryptography misuse includes weak primitives, homegrown protocols, bad randomness, bad modes, and unsafe key handling.',
    'prefer vetted libraries and threat-specific design instead of inventing crypto.',
    ['Key Management', 'Randomness', 'Encryption', 'Signing'],
  ],
  [
    'key-rotation',
    'Key Rotation',
    'Replacing cryptographic keys safely',
    'intermediate',
    'Key rotation changes encryption, signing, or credential keys while keeping systems able to transition safely.',
    'ask how old and new keys overlap so rotation does not become an outage.',
    ['KMS', 'Key ID', 'Revocation', 'Envelope Encryption'],
  ],
  [
    'service-least-privilege',
    'Service Least Privilege',
    'Narrow rights for application identities',
    'beginner',
    'Service least privilege limits application identities to the actions and resources required for their workload.',
    'review service permissions as carefully as human admin permissions.',
    ['IAM', 'Service Account', 'Workload Identity', 'Blast Radius'],
  ],
  [
    'container-scanning',
    'Container Scanning',
    'Checking images before deployment',
    'beginner',
    'Container scanning inspects image layers and packages for known vulnerabilities and policy issues.',
    'ask which base image and dependency path create the finding.',
    ['Image', 'CVE', 'SBOM', 'Registry'],
  ],
  [
    'iac-scanning',
    'IaC Scanning',
    'Reviewing infrastructure code for risk',
    'beginner',
    'Infrastructure-as-code scanning checks templates and plans for risky configuration before cloud resources are created.',
    'catch exposed storage and overbroad policy in review before they become deployed drift.',
    ['Terraform', 'Policy as Code', 'Cloud Security', 'CI'],
  ],
  [
    'artifact-signing',
    'Artifact Signing',
    'Proving what built and published software',
    'intermediate',
    'Artifact signing adds cryptographic evidence that a software artifact came from an expected build identity or process.',
    'ask what verifies signatures at deployment, not only who signs them.',
    ['Provenance', 'Cosign', 'Supply Chain', 'Admission'],
  ],
  [
    'branch-protection',
    'Branch Protection',
    'Guardrails around source changes',
    'beginner',
    'Branch protection enforces review, checks, permissions, and history rules before changes land in protected code branches.',
    'treat source control policy as a security control for the delivery path.',
    ['Pull Request', 'CI', 'Code Owner', 'Supply Chain'],
  ],
  [
    'vulnerability-triage',
    'Vulnerability Triage',
    'Deciding what needs action now',
    'beginner',
    'Vulnerability triage evaluates exploitability, exposure, impact, fix availability, compensating controls, and ownership.',
    'prioritize the reachable high-impact path over raw scanner count.',
    ['CVE', 'Risk', 'SLA', 'Remediation'],
  ],
  [
    'cvss-risk',
    'CVSS vs Business Risk',
    'Severity score is not full context',
    'intermediate',
    'CVSS summarizes technical severity while business risk also depends on exposure, asset value, exploitability, and controls.',
    'use severity as input, then explain the environment-specific risk decision.',
    ['Vulnerability', 'Exposure', 'Impact', 'Risk Acceptance'],
  ],
  [
    'remediation-sla',
    'Remediation SLA',
    'A time target for fixing risk',
    'beginner',
    'A remediation SLA sets expected fix windows for vulnerability classes or risk levels.',
    'ask what exception path exists when a fix window conflicts with operational safety.',
    ['Vulnerability', 'Exception', 'Patch', 'Risk'],
  ],
  [
    'pentest',
    'Penetration Test',
    'Human-led security testing of attack paths',
    'beginner',
    'A penetration test evaluates whether realistic attack paths can exploit a system under agreed scope.',
    'ask what scope, assumptions, and remediation evidence the pentest will produce.',
    ['Scope', 'Finding', 'Attack Path', 'Retest'],
  ],
  [
    'bug-bounty',
    'Bug Bounty',
    'External reports rewarded by policy',
    'beginner',
    'A bug bounty program invites researchers to report qualifying vulnerabilities under rules and rewards.',
    'plan intake, triage, communication, and duplicates before inviting external reports.',
    ['Disclosure', 'Researcher', 'Triage', 'Severity'],
  ],
  [
    'secure-sdlc',
    'Secure SDLC',
    'Security integrated into delivery',
    'beginner',
    'A secure SDLC adds security activities at design, code, build, test, release, and operations stages.',
    'place each control where it finds risk early without blocking low-value work.',
    ['Threat Model', 'SAST', 'Release Gate', 'Security Champion'],
  ],
  [
    'security-champion',
    'Security Champion',
    'A team contact for security practice',
    'beginner',
    'A security champion helps a delivery team apply security guidance, escalate questions, and improve habits.',
    'use champions to scale expertise while keeping security accountability shared.',
    ['Secure SDLC', 'Training', 'Threat Model', 'Team'],
  ],
  [
    'release-gate',
    'Security Release Gate',
    'A defined security condition before shipping',
    'intermediate',
    'A release gate blocks or escalates shipping when defined security criteria are not satisfied.',
    'keep gates explicit, risk-based, and paired with a documented exception path.',
    ['Policy', 'Exception', 'CI', 'Risk Acceptance'],
  ],
];

export const observabilityCards = buildCards('observability', observabilitySeeds);
export const identityCards = buildCards('identity', identitySeeds);
export const architectureCards = buildCards('architecture', architectureSeeds);
export const appsecCards = buildCards('appsec', appsecSeeds);
